// Generated by scripts/build_interaction_chart.py. Do not edit by hand.
//
// Source: TripSit's drug combination chart, https://combo.tripsit.me
// Data:   https://github.com/TripSit/drugs (combos.json)
//
// This file records what the chart says, not what ChillMate says. The two are
// compared at run time by `SubstanceInteraction.corroboration`, and every row
// of the app's own table is re-checked against this one by `InteractionChartTests`.

public enum InteractionChart {
    /// A chart grading, in ChillMate's own severity terms.
    ///
    /// The chart's four low-risk gradings all sit below ChillMate's mildest
    /// level, so they collapse into `lowRisk`.
    public enum Grading: Int, Comparable, Sendable {
        case lowRisk = 0
        case caution = 1
        case serious = 2
        case critical = 3

        public static func < (lhs: Grading, rhs: Grading) -> Bool { lhs.rawValue < rhs.rawValue }
    }

    public struct Entry: Sendable {
        public let grading: Grading
        /// True when the pair was read against a near neighbour rather than
        /// itself: 3-MMC against mephedrone, or the psychedelics group against
        /// the most severe of LSD and mushrooms. Shown to the reader as a
        /// weaker claim than an exact match.
        public let isApproximate: Bool
    }

    /// 48 of the pairs ChillMate can make. The rest are not on the chart.
    public static let entries: [String: Entry] = [
        "alcohol+benzodiazepines": Entry(grading: .critical, isApproximate: false),
        "alcohol+cannabis": Entry(grading: .lowRisk, isApproximate: false),
        "alcohol+cocaine": Entry(grading: .serious, isApproximate: false),
        "alcohol+gbl": Entry(grading: .critical, isApproximate: false),
        "alcohol+ghb": Entry(grading: .critical, isApproximate: false),
        "alcohol+ketamine": Entry(grading: .critical, isApproximate: false),
        "alcohol+mdma": Entry(grading: .caution, isApproximate: false),
        "alcohol+methamphetamine": Entry(grading: .caution, isApproximate: true),
        "alcohol+psychedelics": Entry(grading: .lowRisk, isApproximate: true),
        "benzodiazepines+cannabis": Entry(grading: .lowRisk, isApproximate: false),
        "benzodiazepines+cocaine": Entry(grading: .lowRisk, isApproximate: false),
        "benzodiazepines+gbl": Entry(grading: .critical, isApproximate: false),
        "benzodiazepines+ghb": Entry(grading: .critical, isApproximate: false),
        "benzodiazepines+ketamine": Entry(grading: .caution, isApproximate: false),
        "benzodiazepines+mdma": Entry(grading: .lowRisk, isApproximate: false),
        "benzodiazepines+methamphetamine": Entry(grading: .lowRisk, isApproximate: true),
        "benzodiazepines+psychedelics": Entry(grading: .lowRisk, isApproximate: true),
        "cannabis+cocaine": Entry(grading: .caution, isApproximate: false),
        "cannabis+gbl": Entry(grading: .lowRisk, isApproximate: false),
        "cannabis+ghb": Entry(grading: .lowRisk, isApproximate: false),
        "cannabis+ketamine": Entry(grading: .lowRisk, isApproximate: false),
        "cannabis+mdma": Entry(grading: .lowRisk, isApproximate: false),
        "cannabis+methamphetamine": Entry(grading: .caution, isApproximate: true),
        "cannabis+psychedelics": Entry(grading: .caution, isApproximate: true),
        "cocaine+gbl": Entry(grading: .caution, isApproximate: false),
        "cocaine+ghb": Entry(grading: .caution, isApproximate: false),
        "cocaine+ketamine": Entry(grading: .caution, isApproximate: false),
        "cocaine+mdma": Entry(grading: .caution, isApproximate: false),
        "cocaine+methamphetamine": Entry(grading: .caution, isApproximate: true),
        "cocaine+psychedelics": Entry(grading: .caution, isApproximate: true),
        "gbl+ketamine": Entry(grading: .critical, isApproximate: false),
        "gbl+mdma": Entry(grading: .caution, isApproximate: false),
        "gbl+methamphetamine": Entry(grading: .caution, isApproximate: true),
        "gbl+psychedelics": Entry(grading: .lowRisk, isApproximate: true),
        "gbl+threeMMC": Entry(grading: .caution, isApproximate: true),
        "ghb+ketamine": Entry(grading: .critical, isApproximate: false),
        "ghb+mdma": Entry(grading: .caution, isApproximate: false),
        "ghb+methamphetamine": Entry(grading: .caution, isApproximate: true),
        "ghb+psychedelics": Entry(grading: .lowRisk, isApproximate: true),
        "ghb+threeMMC": Entry(grading: .caution, isApproximate: true),
        "ketamine+mdma": Entry(grading: .lowRisk, isApproximate: false),
        "ketamine+methamphetamine": Entry(grading: .caution, isApproximate: true),
        "ketamine+psychedelics": Entry(grading: .lowRisk, isApproximate: true),
        "mdma+methamphetamine": Entry(grading: .caution, isApproximate: true),
        "mdma+psychedelics": Entry(grading: .lowRisk, isApproximate: true),
        "mdma+threeMMC": Entry(grading: .critical, isApproximate: true),
        "methamphetamine+psychedelics": Entry(grading: .caution, isApproximate: true),
        "psychedelics+threeMMC": Entry(grading: .caution, isApproximate: true),
    ]

    /// Looks up a pair. The key is the two raw case names, sorted, joined by `+`.
    public static func entry(for substances: Set<Substance>) -> Entry? {
        guard substances.count == 2 else { return nil }
        let key = substances.map(\.chartKey).sorted().joined(separator: "+")
        return entries[key]
    }
}
