#!/usr/bin/env python3
"""Generate ChillMate/InteractionChart.swift from TripSit's combination chart.

TripSit publishes its drug combination chart as a data file, and it is the
reference most harm-reduction services work from. This script turns the pairs it
covers into a compiled-in lookup so `SubstanceInteraction` can say, per row,
whether its own severity matches the chart, sits above it, or is not covered
by it at all.

The point is that the claim cannot drift. The table is generated, never
hand-edited, and `InteractionChartTests` re-checks every row in the app's own
table against it.

Usage:
    curl -sSL https://raw.githubusercontent.com/TripSit/drugs/main/combos.json \
        -o /tmp/combos.json
    python3 scripts/build_interaction_chart.py /tmp/combos.json
"""
import json
import sys

# How ChillMate's substances line up with the chart's names.
#
# Three of ours have no entry at all — poppers and the two sildenafil products —
# so those rows carry `.notOnChart` and rest on the sources named beside them.
#
# Two mappings are judgements rather than matches, and are marked as such in the
# generated file so nobody later mistakes them for exact:
#   * 3-MMC is read against mephedrone (4-MMC), its positional isomer. The chart
#     has no 3-MMC row.
#   * "Psychedelics" is one entry in ChillMate and several on the chart, so the
#     most severe of LSD and mushrooms is taken.
MAPPING = {
    "cannabis": ["cannabis"],
    "alcohol": ["alcohol"],
    "mdma": ["mdma"],
    "threeMMC": ["mephedrone"],
    "ketamine": ["ketamine"],
    "ghb": ["ghb/gbl"],
    "gbl": ["ghb/gbl"],
    "cocaine": ["cocaine"],
    "psychedelics": ["lsd", "mushrooms"],
    "benzodiazepines": ["benzodiazepines"],
}

APPROXIMATE = {"threeMMC", "psychedelics"}

# The chart's four low-risk gradings all sit below ChillMate's mildest level, so
# they collapse to one case. The three above it map one-for-one.
LEVELS = {
    "Low Risk & Decrease": "lowRisk",
    "Low Risk & No Synergy": "lowRisk",
    "Low Risk & Synergy": "lowRisk",
    "Caution": "caution",
    "Unsafe": "serious",
    "Dangerous": "critical",
}
RANK = {"lowRisk": 0, "caution": 1, "serious": 2, "critical": 3}


def main() -> int:
    with open(sys.argv[1]) as handle:
        chart = json.load(handle)

    rows = {}
    names = sorted(MAPPING)
    for i, first in enumerate(names):
        for second in names[i + 1:]:
            best = None
            for left in MAPPING[first]:
                for right in MAPPING[second]:
                    if left == right:
                        continue
                    entry = (chart.get(left) or {}).get(right) or (chart.get(right) or {}).get(left)
                    if not entry:
                        continue
                    level = LEVELS.get(entry["status"])
                    if level is None:
                        raise SystemExit(f"unmapped chart status {entry['status']!r}")
                    if best is None or RANK[level] > RANK[best]:
                        best = level
            if best is not None:
                key = "+".join(sorted([first, second]))
                approximate = bool({first, second} & APPROXIMATE)
                rows[key] = (best, approximate)

    lines = [
        "// Generated by scripts/build_interaction_chart.py. Do not edit by hand.",
        "//",
        "// Source: TripSit's drug combination chart, https://combo.tripsit.me",
        "// Data:   https://github.com/TripSit/drugs (combos.json)",
        "//",
        "// This file records what the chart says, not what ChillMate says. The two are",
        "// compared at run time by `SubstanceInteraction.corroboration`, and every row",
        "// of the app's own table is re-checked against this one by `InteractionChartTests`.",
        "",
        "enum InteractionChart {",
        "    /// A chart grading, in ChillMate's own severity terms.",
        "    ///",
        "    /// The chart's four low-risk gradings all sit below ChillMate's mildest",
        "    /// level, so they collapse into `lowRisk`.",
        "    enum Grading: Int, Comparable, Sendable {",
        "        case lowRisk = 0",
        "        case caution = 1",
        "        case serious = 2",
        "        case critical = 3",
        "",
        "        static func < (lhs: Grading, rhs: Grading) -> Bool { lhs.rawValue < rhs.rawValue }",
        "    }",
        "",
        "    struct Entry: Sendable {",
        "        let grading: Grading",
        "        /// True when the pair was read against a near neighbour rather than",
        "        /// itself: 3-MMC against mephedrone, or the psychedelics group against",
        "        /// the most severe of LSD and mushrooms. Shown to the reader as a",
        "        /// weaker claim than an exact match.",
        "        let isApproximate: Bool",
        "    }",
        "",
        f"    /// {len(rows)} of the pairs ChillMate can make. The rest are not on the chart.",
        "    static let entries: [String: Entry] = [",
    ]
    for key in sorted(rows):
        grading, approximate = rows[key]
        lines.append(
            f'        "{key}": Entry(grading: .{grading}, isApproximate: {str(approximate).lower()}),'
        )
    lines += [
        "    ]",
        "",
        "    /// Looks up a pair. The key is the two raw case names, sorted, joined by `+`.",
        "    static func entry(for substances: Set<Substance>) -> Entry? {",
        "        guard substances.count == 2 else { return nil }",
        "        let key = substances.map(\\.chartKey).sorted().joined(separator: \"+\")",
        "        return entries[key]",
        "    }",
        "}",
        "",
    ]
    with open("ChillMate/InteractionChart.swift", "w") as handle:
        handle.write("\n".join(lines))
    print(f"wrote ChillMate/InteractionChart.swift with {len(rows)} pairs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
