# -*- coding: utf-8 -*-
"""Dutch copy. Translated from lang_en, in the tone the app itself uses.

Dutch is the primary audience, so this file gets the closest reading. It says
"je", never "u": the app does, and a safety tool that addresses you formally at
four in the morning has picked the wrong register.
"""

S = {
    "skip": "Naar de inhoud",
    "nav_home": "Home",
    "nav_privacy": "Privacy",
    "nav_support": "Hulp",
    "nav_about": "Over",
    "nav_github": "GitHub",
    "lang_label": "Taal",
    "theme_dark": "Donker",
    "theme_light": "Licht",
    "theme_hint": "Wissel van kleurthema",
    "to_top": "Terug naar boven",
    "made": "gemaakt door één persoon in Nederland",
    "copy": "Kopiëren",
    "copied": "Gekopieerd",
    "call": "Bel",
    "open": "Open",
    "policy_en_note": "Er is een Nederlandse vertaling van het privacybeleid. De Engelse tekst is de gezaghebbende versie: bij verschil geldt die.",

    "disclaimer": "ChillMate ondersteunt reflectie, planning en je eigen welzijn. Het vervangt geen behandelaar en bepaalt nooit of iets veilig is. Als iemand in direct gevaar kan zijn, bel dan je lokale alarmnummer.",

    "cat_emergency": "Hulpdiensten",
    "cat_crisis": "Crisis en zelfmoordpreventie",
    "cat_sexual_health": "Seksuele gezondheid en soa-tests",
    "cat_gp": "Je huisarts",
    "cat_drugs": "Drugsinformatie en harm reduction",
    "cat_assault": "Na seksueel geweld",
    "cat_lgbtq": "LHBTIQ+ steun",
    "cat_emergency_d": "Direct gevaar, bewusteloosheid, of iemand die niet wakker te krijgen is.",
    "cat_crisis_d": "Gratis en vertrouwelijk, als je jezelf iets zou kunnen aandoen of je niet veilig voelt.",
    "cat_sexual_health_d": "Soa-testen, PrEP, PEP-vragen, vaccinatie en seksuele gezondheid.",
    "cat_gp_d": "Wisselwerking van medicijnen, slaap, mentale gezondheid, middelengebruik en doorverwijzing.",
    "cat_drugs_d": "Betrouwbare, niet-veroordelende drugsinformatie en harm reduction.",
    "cat_assault_d": "Steun na geweld, dwang of twijfel over toestemming.",
    "cat_lgbtq_d": "Een luisterend oor, informatie en doorverwijzing.",
    "cat_generic_local": "Vraag het bij je lokale zorginstelling.",

    "home_title": "ChillMate · Een rustige, privéplek om voor jezelf te zorgen",
    "home_desc": "Een privéoverzicht van je eigen nachten, plannen, herinneringen en veiligheidstools, volledig op je iPhone. Gratis, open source, geen account en geen server.",

    "h1": "Een rustige, privéplek om voor jezelf te zorgen.",
    # Short enough to survive a 1200x630 share card.
    "og_sub": "Geen account. Geen servers. Alles blijft op je iPhone.",
    "og_foot": "Open source · iPhone en Apple Watch",
    "lede": 'Je nachten, plannen en veiligheidstools in één privéoverzicht op je iPhone. Gratis, open source, en er is geen server.',
    "cta_notify": "Laat het me weten als hij er is",
    "cta_see": "Bekijk hoe het werkt",
    "status_note": "Nog niet in de App Store. Stuur een lege mail en je hoort één keer van me, op de dag dat hij er is.",
    "notify_subject": "Laat het me weten als ChillMate er is",
    "notify_body": "Je hoeft niets te schrijven. Ik antwoord één keer, op de dag van de lancering, en verwijder daarna je adres.",

    "audience_eyebrow": "Voor wie het is",
    "audience_h2": "Gemaakt voor de nachten waar dit echt over gaat",
    "audience_p": 'Chems, hookups, of allebei. ChillMate heeft daar geen mening over en zal je nooit vragen een nacht te verantwoorden.',
    "audience_points": [
        "Een risicocheck die weet wat je al gebruikt, inclusief je eigen recept.",
        "Een check-intimer, zodat iemand weet dat je thuis bent zonder dat je hoeft te appen.",
        "Een PEP-venster dat begint te tellen op het moment dat het ertoe kan doen.",
        "Testherinneringen die op je vergrendelscherm nooit zeggen waarom.",
    ],
    "audience_chill": "De app noemt een nacht een <strong>Chill</strong>. De jouwe, wat het ook was.",

    "walk_eyebrow": "Een kijkje binnen",
    "walk_h2": "Vijf schermen, en waar ze voor zijn.",
    "walk": [
        ('Hij schikt zichzelf', 'Wat het vannacht ook werd', 'Leg een nacht vast en het beginscherm herschikt zich eromheen. Hier heeft hij bedacht dat een PEP-gesprek de moeite waard kan zijn, en de aftelling apart bovenaan gezet.'),
        ('Hij zegt wat bekend is', 'En weigert te zeggen dat het veilig is', 'Kies wat er speelt, inclusief je eigen medicijnen, en hij vertelt wat er over die combinatie gedocumenteerd is. Er is geen groen licht.'),
        ('Een kamer met het licht gedimd', 'Voor als het al misgaat', 'Weinig prikkels, één ding tegelijk. Adem, loop de groundingstappen door, en bel pas iemand als je dat zelf wilt.'),
        ('Echte hulpverlening, offline', 'Hulp van mensen, niet van een app', 'Crisislijnen, seksuele gezondheid, drugs en LHBTIQ+ steun voor het land dat je instelt. Een lijst op je telefoon, dus hij werkt zonder bereik.'),
        ('Een eerlijke kaart van je gegevens', 'In de app, niet alleen in een beleidstekst', 'Wat er op het toestel staat, wat er in een versleutelde back-up zou zitten, en wat ChillMate nooit verstuurt. Daar zou je geen beleidstekst voor hoeven lezen.'),
    ],

    "night_eyebrow": "Hoe het past",
    "night_h2": "Eén nacht, in drie momenten.",
    "night": [
        ('Voor je gaat', 'Beslis nu het makkelijk is', 'Leg de combinatie langs de risicocheck, zet vast waar je wel en geen zin in hebt, en start een check-intimer. Vijf minuten terwijl je nog helder bent.'),
        ('Als je op stap bent', 'Eén tik, niets typen', 'De timer vraagt of het goed gaat. Hulp zoeken kent je vertrouwenscontact en het juiste alarmnummer voor waar je bent al. Je horloge kan voor je antwoorden.'),
        ('De ochtend erna', 'Onthoud het zoals het was', 'Slaap, hoe je je voelt, wat echt hielp. Een minuut nu is het deel waar je over drie maanden blij mee bent.'),
    ],

    "features_eyebrow": "Wat erin zit",
    "features": [
        ("book", "tint-blue", "Privélogboek",
         "Leg een nacht vast zoals jij hem wilt onthouden: slaap, hoe je je voelde, en wat daarna hielp."),
        ("chart", "tint-mint", "Jouw patronen",
         "Overzichten over 30 en 90 dagen van wat er echt verandert, en een dagscore die alleen jij ooit ziet."),
        ("life", "tint-purple", "Zorgtools",
         "Ademhaling, een pauze bij drang, een plan voor een veiligere sessie, en een route naar huis als je die wilt."),
        ("flask", "tint-pink", "Risicocheck",
         "Waarschuwingen in gewone taal over combinaties, inclusief de medicijnen die je al gebruikt."),
        ("bell", "tint-amber", "Herinneringen die passen",
         "Check-intimers, een PEP-venster en testherinneringen, discreet geformuleerd als je dat liever hebt."),
        ("watch", "tint-blue", "Op je pols",
         "Timers, check-ins en een noodnummer op Apple Watch, zonder naar je telefoon te grijpen."),
    ],

    "foryou_eyebrow": "Is dit iets voor jou",
    "foryou_h2": "Hieraan merk je het.",
    "foryou": [
        "Je wilt gisternacht precies onthouden, niet vaag, en niet door iemand anders.",
        "Je gebruikt PrEP en hebt liever niet dat de herinnering PrEP op je vergrendelscherm zet.",
        "Je wilt een reden om bij iemand in te checken die geen heel gesprek is.",
        "Je hebt je doordeweeks weleens afgevraagd of het vaker is dan vroeger.",
        "Je wilt het alarmnummer van waar je bent, zonder een browser te ontgrendelen.",
    ],
    "foryou_not": "Het is waarschijnlijk niets voor je als je iets zoekt dat de nacht voor je beoordeelt, je gedrag een cijfer geeft, of zegt dat een combinatie veilig is. Dat doet het alle drie met opzet niet.",

    "privacy_eyebrow": "Privé van opzet",
    "privacy_h2": "Je telefoon, en nergens anders",
    "privacy_intro": 'Privacy is hier geen instelling. Het is de vorm van de app.',
    "privacy_checks": [
        'Zet er Face ID of een pincode op, met alles versleuteld op het toestel.',
        'Back-ups zijn optioneel en versleuteld, en gaan naar je eigen iCloud Drive.',
        'Meldingen kunnen bewust vaag blijven op je vergrendelscherm.',
    ],
    "privacy_link": "Lees het volledige privacybeleid",

    "proof_eyebrow": "Controleer het zelf",
    "proof_h2": "Geloof me niet op mijn woord",
    "proof_p": 'ChillMate is open source. Elke regel die je gegevens aanraakt staat openbaar, en dat maakt van de belofte hierboven iets dat je kunt controleren.',
    "proof_fact": 'In de code van de app staat geen enkele netwerkaanroep. Geen analytics-SDK, geen crashrapportage, nergens een <code>URLSession</code>. Het enige dat je telefoon verlaat, is wat jij aantikt.',
    "proof_cta_repo": "Lees de broncode",
    "proof_cta_store": "Waar je gegevens staan",
    "proof_caption": "Gecontroleerd op ChillMate 4.2.1 (build 422).",

    "diagram_title": "Waar je gegevens heen gaan",
    "diagram_you": "Jij",
    "diagram_phone": "Je iPhone",
    "diagram_icloud": "Jouw iCloud",
    "diagram_optional": "optioneel, versleuteld",
    "diagram_server": "Mijn servers",
    "diagram_none": "die zijn er niet",

    "refuse_eyebrow": "Met opzet",
    "refuse_h2": "Wat hij niet doet",
    "refuse_p": "Het meeste werk zat in wat hij níét doet. Dat is lastiger vol te houden dan functies, want elk ervan is iets waar uiteindelijk iemand om vraagt.",
    "refuse": [
        ("Hij zegt niet dat iets veilig is.", "Hij laat zien wat er over een combinatie gedocumenteerd is en geeft de beslissing aan jou terug, want hij kent jouw lichaam, jouw dosis en jouw nacht niet."),
        ("Hij geeft jou als persoon geen cijfer.", "Er is een getal voor de dag, dat blijft op je telefoon, en er wordt niets mee ontgrendeld of onthouden."),
        ("Hij zeurt niet.", "Elke herinnering staat uit tot jij hem aanzet, en kan zo geformuleerd worden dat een vergrendelscherm niets prijsgeeft."),
        ("Hij wil geen account.", "Daar zou een server bij horen, en een server is een kopie van jou op een plek waar jij niet bij kunt."),
        ("Hij laat je niet betalen.", "Alles gratis. De fooi ontgrendelt niets, want een veiligheidstool achter een betaalmuur is geen veiligheidstool."),
    ],

    "watch_h3": "Hij werkt terwijl je telefoon in je zak blijft",
    "watch_p": "Dosistimers, hydratatie, discrete check-ins, een ademhalingsoefening en met één tik je vertrouwenscontact of het lokale alarmnummer, allemaal op Apple Watch, plus complicaties voor je wijzerplaat en de Smart Stack.",
    "watch_quote": "Als iets niet goed voelt, zoek hulp. Je bent niet in de problemen.",
    "watch_quote_note": "Het hele Veiligheid-scherm op het horloge, inclusief die woorden.",
    "langs_h3": "Hij werkt in jouw taal",
    "langs_p": "De app en deze site zijn er in het Engels, Nederlands, Duits, Frans en Spaans. De hulpbronnen volgen het land dat je instelt, niet de taal die je leest, want dat zijn twee verschillende vragen.",

    "faq_teaser_eyebrow": "Voor je het vraagt",
    "faq_teaser_h2": "De drie vragen die iedereen stelt.",
    "faq_teaser_link": "De rest van de vragen, en echte hulpdiensten",

    "support_title": "ChillMate · Hulp en ondersteuning",
    "support_desc": "Crisislijnen en zorgdiensten voor jouw land, offline en printbaar, plus veelgestelde vragen en hoe je mij bereikt.",
    "support_h1": "Hulp, en hoe je mij bereikt",
    "support_lede": "Eerst echte hulpverlening, want daar is deze pagina het nuttigst voor. Vragen over de app staan verderop, en er leest één persoon elk bericht.",
    "support_urgent": "<strong>Wacht in een noodgeval niet op de app.</strong> Als jij of iemand anders in direct gevaar kan zijn, bel dan nu je lokale alarmnummer.",
    "support_contact_eyebrow": "Neem contact op",
    "support_contact_h2": "Contact",
    "support_contact_p": "Mail naar {email}. Een antwoord duurt meestal een paar dagen. Je iOS-versie en wat je deed toen het misging, helpen enorm.",
    "support_email_btn": "Mail mij",
    "support_issue_btn": "Meld een probleem",
    "support_faq_eyebrow": "Veelgestelde vragen",
    "support_help_eyebrow": "Echte hulpverlening",
    "support_help_h2": "Hulp van mensen, niet van een app",
    "support_help_p": "ChillMate is geen crisisdienst. Kies waar je bent, dan kunnen deze organisaties je direct helpen. Deze pagina is printbaar en werkt zonder bereik, want dat is precies wanneer deze nummers ertoe doen.",
    "support_country_label": "Waar ben je?",
    "support_emergency_is": "Alarmnummer hier:",
    "support_emergency_local": "je lokale alarmnummer",
    "support_print": "Print deze pagina",

    "faq": [
        ("Zijn mijn gegevens privé?",
         "Ja, en je hoeft me niet te geloven. ChillMate houdt alles op je iPhone, heeft geen account en geen server, en draait geen advertenties, analytics of trackers. De app is open source, dus je kunt precies nalezen wat er met je invoer gebeurt."),
        ("Wat kost het?",
         "Niets, en er is geen betaalde versie. Een optionele fooi loopt via Apple In-App Purchase en ontgrendelt helemaal niets. Elke functie is er voor iedereen, want een veiligheidstool achter een betaalmuur is geen veiligheidstool."),
        ("Zegt hij of iets veilig is?",
         "Nee, en dat zal hij nooit doen. De risicocheck laat zien wat er over een combinatie gedocumenteerd is, ook met medicijnen die je al gebruikt, en stopt daar. Er is geen groen licht. Voor alles wat ertoe doet is een arts of apotheker de juiste plek."),
        ("Hoe maak ik een back-up of stap ik over naar een nieuwe telefoon?",
         "Zet iCloud-back-up aan in Instellingen om een versleutelde back-up in je eigen iCloud Drive te bewaren, of exporteer zelf een versleuteld back-upbestand. Op een nieuw toestel herstel je vanuit iCloud of importeer je dat bestand tijdens het instellen."),
        ("Hoe vergrendel of verberg ik de app?",
         "Zet in Instellingen, onder Privacy en vergrendeling, Face ID aan of stel een pincode in. Je kunt ook discrete meldingen aanzetten zodat je vergrendelscherm niets prijsgeeft, en ChillMate verbergt zijn inhoud in de app-switcher en tijdens schermopname of spiegelen. Eén tik maakt het scherm zwart met een maantje."),
        ("Hoe verwijder ik mijn gegevens?",
         "Losse items of alles in één keer, binnen de app. De app verwijderen wist de lokale gegevens, en iCloud-gegevens haal je weg via de back-upinstellingen of via iCloud. Er is nergens anders een kopie waar je naar zou moeten vragen."),
        ("Welke landen worden ondersteund?",
         "ChillMate werkt overal. De hulpbronnen volgen het land dat je bij het instellen kiest, met ingebouwde diensten voor Nederland, België, Duitsland, het Verenigd Koninkrijk, Ierland, Frankrijk, Spanje, de Verenigde Staten en Australië, en internationale alternatieven daarbuiten."),
        ("Welke talen spreekt hij?",
         "Engels, Nederlands, Duits, Frans en Spaans, op de telefoon en op Apple Watch. Stel de taal in de app of in iOS-instellingen in; de laatste die je wijzigde is degene die geldt."),
    ],
    "human": 'Ik ben één persoon in Nederland. Ik maakte de app die ik wilde dat bestond, en ik zie nooit iets van wat jij erin zet.',
    "footnotes": [
        'Nergens in de app netwerkverkeer.',
        'Synchronisatie gaat naar je eigen privédatabase.',
        'De pincode: 200.000 PBKDF2-rondes, in de Keychain.',
        'Verborgen in de app-switcher en tijdens schermopname.',
        'Back-ups verzegeld met AES-GCM.',
        'Meldingteksten die niets prijsgeven.',
        "Samenvattingen draaien op Apple's model op het toestel.",
        'De 30 combinaties hierboven.',
        "De hulpgids voor 10 regio's.",
    ],
    "statement2_big": 'Hij zegt nooit dat iets veilig is.',
    "statement2_note": 'Niet de risicocheck, niet de samenvattingen, nergens. Hij laat zien wat bekend is en geeft de beslissing aan jou terug.',
    "nav_howto": 'Hoe het werkt',
    "howto_title": 'ChillMate · Hoe het werkt',
    "howto_desc": 'Eén nacht in drie momenten, wat de app niet doet, wat erin zit, en de Apple Watch.',
    "howto_h1": 'Hoe het werkt',
    "howto_lede": 'De delen die niet op de voorpagina pasten: de vorm van een nacht, de dingen die hij niet doet, en wat er echt in zit.',
    "howto_back": 'Terug naar de voorpagina',
    "demo_meds_label": 'Wat je al gebruikt',
    "demo_meds_ph": 'Naam van medicijn, optioneel',
    "demo_timing_label": 'Hoe kort op elkaar',
    "demo_assess_label": 'Vaste checks',
    "demo_share": 'Kopieer een link hiernaartoe',
    "demo_shared": 'Link gekopieerd',
    "demo_print": 'Print dit',
    "demo_meds_hit": 'Herkend',
    "demo_meds_none": 'Geen bekende groep herkend.',
    "faq_teaser_indices": [0, 1, 2],

    "nav_chapters": [("who", "Voor wie"), ("inside", "Binnenkijken"),
                     ("try", "Probeer het"), ("privacy", "Privacy"), ("specs", "Specs")],
    "scroll_cue": "Scroll",

    "statement": [("0", "servers"), ("0", "accounts"), ("0", "trackers")],
    "statement_note": "Geen belofte. Een bouwwijze. Alles hieronder legt uit hoe, met een link naar de regel code die het bewijst.",

    "demo_eyebrow": "Probeer het",
    "demo_h2": "Dit is de echte risicocheck.",
    "demo_p": 'Geen schermafbeelding ervan. Dezelfde 30 combinaties, dezelfde woorden, hier draaiend.',
    "demo_pick": "Kies wat er speelt",
    "demo_none_title": "Niets gedocumenteerd voor deze combinatie",
    "demo_none_body": "Dat is niet hetzelfde als veilig. Het betekent dat deze tabel er niets over heeft, en deze tabel is over niets het laatste woord.",
    "demo_empty": 'Kies iets, of typ een medicijn, om te zien wat de app zou zeggen.',
    "demo_reset": "Wissen",
    "demo_note": "Draait volledig in deze pagina. Wat je hier aantikt gaat nergens heen, om dezelfde reden als in de app.",
    "demo_try": "Probeer GHB en alcohol",

    "specs_eyebrow": "De details",
    "specs_h2": "Specificaties",
    "specs": [
        ("Vereist", "iPhone met iOS 26 of nieuwer"),
        ("Apple Watch", "Eigen app, watchOS 26 of nieuwer"),
        ("Prijs", "Gratis. Geen betaalde versie, geen abonnement, geen advertenties."),
        ("Account", "Geen. Er valt niets aan te melden."),
        ("Verzamelde gegevens", "Geen"),
        ("Talen", "English, Nederlands, Deutsch, Français, Español"),
        ("Hulpdiensten", "10 regio's, op het toestel, werkt offline"),
        ("Gecheckte combinaties", "30 gedocumenteerde interacties, op het toestel"),
        ("Geschreven samenvattingen", "Op het toestel, Apple Foundation Models"),
        ("Synchronisatie en back-up", "Optioneel, versleuteld, je eigen iCloud"),
        ("Vergrendeling", "Face ID, of een pincode met 200.000 PBKDF2-rondes"),
        ("Broncode", "Open, MIT-licentie"),
        ("Versie", "4.2.1 (build 422)"),
    ],

    "footnotes_title": "Elke bewering op deze pagina, en waar je hem controleert",
    "footnotes_intro": "Marketingpagina's verwijzen met voetnoten naar de kleine lettertjes. Deze verwijst naar de broncode.",
}
