# -*- coding: utf-8 -*-
"""Spanish copy. Translated from lang_en.

"tú", matching the app and matching how this audience is addressed in Spanish
harm-reduction material. Peninsular Spanish, since that is the region the built
in services (Energy Control, FELGTBI+, 016, 024) belong to.
"""

S = {
    "skip": "Saltar al contenido",
    "nav_home": "Inicio",
    "nav_privacy": "Privacidad",
    "nav_support": "Ayuda",
    "nav_about": "Acerca de",
    "nav_github": "GitHub",
    "lang_label": "Idioma",
    "theme_dark": "Oscuro",
    "theme_light": "Claro",
    "theme_hint": "Cambiar de tema",
    "to_top": "Volver arriba",
    "made": "hecho por una sola persona en los Países Bajos",
    "copy": "Copiar",
    "copied": "Copiado",
    "call": "Llamar",
    "open": "Abrir",
    "policy_en_note": "La política de privacidad existe en inglés y neerlandés. El texto en inglés es el que prevalece.",

    "disclaimer": "ChillMate acompaña la reflexión, la planificación y tu bienestar. No sustituye a un profesional y nunca decide si algo es seguro. Si alguien puede estar en peligro inmediato, llama a tu número de emergencias local.",

    "cat_emergency": "Emergencias",
    "cat_crisis": "Crisis y prevención del suicidio",
    "cat_sexual_health": "Salud sexual y pruebas de ITS",
    "cat_gp": "Tu médico",
    "cat_drugs": "Información sobre drogas y reducción de daños",
    "cat_assault": "Tras una agresión sexual",
    "cat_lgbtq": "Apoyo LGTBIQ+",
    "cat_emergency_d": "Peligro inmediato, pérdida de conciencia, o alguien que no despierta.",
    "cat_crisis_d": "Gratuito y confidencial, si podrías hacerte daño o no te sientes a salvo.",
    "cat_sexual_health_d": "Pruebas de ITS, PrEP, dudas sobre PEP, vacunación y salud sexual.",
    "cat_gp_d": "Interacciones de medicamentos, sueño, salud mental, consumo y derivaciones.",
    "cat_drugs_d": "Información fiable y sin juicios, y reducción de daños.",
    "cat_assault_d": "Apoyo tras una agresión, coacción o dudas sobre el consentimiento.",
    "cat_lgbtq_d": "Escucha, información y derivación.",
    "cat_generic_local": "Pregunta en tu servicio de salud local.",

    "home_title": "ChillMate · Un lugar tranquilo y privado para cuidarte",
    "home_desc": "Un resumen privado de tus noches, planes, recordatorios y herramientas de seguridad, entero en tu iPhone. Gratis, de código abierto, sin cuenta y sin servidor.",

    "h1": "Un lugar tranquilo y privado para cuidarte.",
    # Short enough to survive a 1200x630 share card.
    "og_sub": "Sin cuenta. Sin servidores. Todo se queda en tu iPhone.",
    "og_foot": "Código abierto · iPhone y Apple Watch",
    "lede": 'Tus noches, planes y herramientas de seguridad en un resumen privado en tu iPhone. Gratis, de código abierto, y sin servidor.',
    "cta_notify": "Avísame cuando salga",
    "cta_see": "Ver cómo funciona",
    "status_note": "Todavía no está en la App Store. Manda un correo vacío y tendrás noticias mías una sola vez, el día que salga.",
    "notify_subject": "Avísame cuando salga ChillMate",
    "notify_body": "No hace falta escribir nada. Respondo una vez, el día del lanzamiento, y después borro tu dirección.",

    "audience_eyebrow": "Para quién es",
    "audience_h2": "Hecho para las noches de las que va esto de verdad",
    "audience_p": 'Chems, ligues, o las dos cosas. ChillMate no tiene opinión al respecto y nunca te pedirá que justifiques una noche.',
    "audience_points": [
        "Un comprobador de riesgos que sabe qué tomas ya, tu propia receta incluida.",
        "Un temporizador de check-in, para que alguien sepa que has llegado sin tener que escribir.",
        "Una ventana de PEP que empieza a contar en el momento en que podría importar.",
        "Recordatorios de pruebas que nunca dicen por qué en tu pantalla de bloqueo.",
    ],
    "audience_chill": "La app llama a una noche un <strong>Chill</strong>. El tuyo, fuera lo que fuera.",

    "walk_eyebrow": "Un vistazo por dentro",
    "walk_h2": "Cinco pantallas, y para qué sirve cada una.",
    "walk": [
        ('Se recoloca solo', 'En lo que sea que acabara la noche', 'Registra una noche y la pantalla de inicio se recoloca a su alrededor. Aquí ha deducido que una conversación sobre PEP podría merecer la pena, y ha puesto la cuenta atrás sola arriba.'),
        ('Dice lo que se sabe', 'Y se niega a decir que es seguro', 'Marca lo que hay en juego, tu medicación incluida, y te enseña qué está documentado sobre esa combinación. No hay luz verde.'),
        ('Una habitación con la luz baja', 'Para cuando ya está yendo mal', 'Poca estimulación, una cosa cada vez. Respira, sigue los pasos de grounding, y llama a alguien solo si tú lo decides.'),
        ('Servicios reales, sin conexión', 'Ayuda de personas, no de una app', 'Líneas de crisis, salud sexual, drogas y apoyo LGTBIQ+ para el país que elijas. Una lista en tu teléfono, así que funciona sin cobertura.'),
        ('Un mapa honesto de tus datos', 'En la app, no solo en una política', 'Qué hay en el dispositivo, qué contendría una copia cifrada, y qué no envía ChillMate nunca. No deberías tener que leer una política para saberlo.'),
    ],

    "night_eyebrow": "Cómo encaja",
    "night_h2": "Una noche, en tres momentos.",
    "night": [
        ('Antes de salir', 'Decide mientras es fácil', 'Pasa la combinación por el comprobador de riesgos, deja claro qué te apetece, y pon un temporizador de check-in. Cinco minutos mientras tienes la cabeza clara.'),
        ('Mientras estás fuera', 'Un toque, sin escribir nada', 'El temporizador pregunta si estás bien. Pedir ayuda ya conoce a tu contacto de confianza y el número de emergencias correcto de donde estés. Tu reloj puede responder por ti.'),
        ('La mañana siguiente', 'Recuérdalo tal cual', 'Sueño, cómo estás, qué ayudó de verdad. Un minuto ahora es la parte que agradecerás dentro de tres meses.'),
    ],

    "features_eyebrow": "Qué lleva dentro",
    "features": [
        ("book", "tint-blue", "Registro privado",
         "Anota una noche como quieras recordarla: sueño, cómo te sentiste, y qué ayudó después."),
        ("chart", "tint-mint", "Tus patrones",
         "Vistas de 30 y 90 días de lo que de verdad cambia, y una puntuación del día que solo ves tú."),
        ("life", "tint-purple", "Herramientas de cuidado",
         "Respiración, una pausa ante el impulso, un plan para una sesión más segura, y una ruta a casa cuando la quieras."),
        ("flask", "tint-pink", "Comprobador de riesgos",
         "Avisos en lenguaje claro sobre combinaciones, incluida la medicación que ya tomas."),
        ("bell", "tint-amber", "Recordatorios que encajan",
         "Temporizadores de check-in, una ventana de PEP y recordatorios de pruebas, con discreción si lo prefieres."),
        ("watch", "tint-blue", "En tu muñeca",
         "Temporizadores, check-ins y un número de emergencia en el Apple Watch, sin sacar el teléfono."),
    ],

    "foryou_eyebrow": "Es esto para ti",
    "foryou_h2": "Lo sabrás por esto.",
    "foryou": [
        "Quieres recordar anoche con precisión, no en vago, y no a través de otra persona.",
        "Tomas PrEP y preferirías que el recordatorio no pusiera PrEP en tu pantalla de bloqueo.",
        "Quieres una excusa para dar señales de vida que no sea una conversación entera.",
        "Te has preguntado, entre semana, si es más a menudo que antes.",
        "Quieres el número de emergencias de donde estás, sin desbloquear un navegador.",
    ],
    "foryou_not": "Seguramente no es para ti si buscas algo que juzgue la noche por ti, ponga nota a tu comportamiento, o te diga que una combinación es segura. No hace ninguna de las tres, a propósito.",

    "privacy_eyebrow": "Privado por diseño",
    "privacy_h2": "Tu teléfono, y ningún otro sitio",
    "privacy_intro": 'Aquí la privacidad no es un ajuste. Es la forma de la app.',
    "privacy_checks": [
        'Bloquéala con Face ID o un PIN, con todo cifrado en el dispositivo.',
        'Las copias de seguridad son opcionales y cifradas, y van a tu propio iCloud Drive.',
        'Las notificaciones pueden quedarse deliberadamente vagas en la pantalla de bloqueo.',
    ],
    "privacy_link": "Leer la política de privacidad completa",

    "proof_eyebrow": "Compruébalo tú",
    "proof_h2": "No me creas sin más",
    "proof_p": 'ChillMate es de código abierto. Cada línea que toca tus datos es pública, y eso convierte la promesa de arriba en algo que puedes comprobar.',
    "proof_fact": 'En el código de la app no hay ni una sola llamada de red. Ningún SDK de analítica, ningún informe de fallos, ninguna <code>URLSession</code>. De tu teléfono solo sale lo que tú tocas.',
    "proof_cta_repo": "Leer el código",
    "proof_cta_store": "Dónde viven tus datos",
    "proof_caption": "Verificado en ChillMate 4.2.1 (build 422).",

    "diagram_title": "Adónde van tus datos",
    "diagram_you": "Tú",
    "diagram_phone": "Tu iPhone",
    "diagram_icloud": "Tu iCloud",
    "diagram_optional": "opcional, cifrado",
    "diagram_server": "Mis servidores",
    "diagram_none": "no existen",

    "refuse_eyebrow": "A propósito",
    "refuse_h2": "Lo que no va a hacer",
    "refuse_p": "La mayor parte del trabajo está en lo que no hace. Eso cuesta más de sostener que las funciones, porque cada una de esas negativas es algo que alguien acabará pidiendo.",
    "refuse": [
        ("No te dirá que algo es seguro.", "Enseña qué está documentado sobre una combinación y te devuelve la decisión, porque no conoce tu cuerpo, tu dosis ni tu noche."),
        ("No te pone nota como persona.", "Hay un número para el día, se queda en tu teléfono, y con él no se desbloquea ni se retiene nada."),
        ("No da la lata.", "Cada recordatorio está apagado hasta que tú lo enciendes, y puede redactarse para que una pantalla de bloqueo no revele nada."),
        ("No quiere una cuenta.", "Eso implicaría un servidor, y un servidor es una copia de ti en un sitio al que tú no llegas."),
        ("No te va a cobrar.", "Todo gratis. La propina no desbloquea nada, porque una herramienta de seguridad tras un muro de pago no lo es."),
    ],

    "watch_h3": "Funciona con el teléfono en el bolsillo",
    "watch_p": "Temporizadores de dosis, hidratación, check-ins discretos, un ejercicio de respiración y un toque para tu contacto de confianza o el número de emergencias local, todo en el Apple Watch, además de complicaciones para la esfera y la Smart Stack.",
    "watch_quote": "Si algo va mal, pide ayuda. No estás en un lío.",
    "watch_quote_note": "La pantalla de Seguridad del reloj entera, con esas palabras incluidas.",
    "langs_h3": "Funciona en tu idioma",
    "langs_p": "La app y este sitio están en inglés, neerlandés, alemán, francés y español. Los recursos de ayuda siguen al país que elijas, no al idioma en que lees, porque son dos preguntas distintas.",

    "faq_teaser_eyebrow": "Antes de que preguntes",
    "faq_teaser_h2": "Las tres preguntas que hace todo el mundo.",
    "faq_teaser_link": "El resto de preguntas, y servicios de ayuda reales",

    "support_title": "ChillMate · Ayuda y apoyo",
    "support_desc": "Líneas de crisis y servicios de salud para tu país, sin conexión e imprimibles, más preguntas frecuentes y cómo localizarme.",
    "support_h1": "Ayuda, y cómo localizarme",
    "support_lede": "Primero los servicios reales, porque para eso sirve mejor esta página. Las preguntas sobre la app están más abajo, y hay una sola persona leyendo cada mensaje.",
    "support_urgent": "<strong>En una emergencia, no esperes a la app.</strong> Si tú u otra persona podéis estar en peligro inmediato, llama ya a tu número de emergencias local.",
    "support_contact_eyebrow": "Escríbeme",
    "support_contact_h2": "Contacto",
    "support_contact_p": "Escribe a {email}. La respuesta suele tardar unos días. Indicar tu versión de iOS y qué estabas haciendo cuando falló ayuda mucho.",
    "support_email_btn": "Escríbeme",
    "support_issue_btn": "Informar de un problema",
    "support_faq_eyebrow": "Preguntas frecuentes",
    "support_help_eyebrow": "Servicios reales",
    "support_help_h2": "Ayuda de personas, no de una app",
    "support_help_p": "ChillMate no es un servicio de crisis. Elige dónde estás y estas organizaciones pueden ayudarte directamente. Esta página se imprime y funciona sin conexión, porque es justo entonces cuando estos números importan.",
    "support_country_label": "¿Dónde estás?",
    "support_emergency_is": "Número de emergencias aquí:",
    "support_emergency_local": "tu número de emergencias local",
    "support_print": "Imprimir esta página",

    "faq": [
        ("¿Mis datos son privados?",
         "Sí, y no hace falta que me creas. ChillMate guarda todo en tu iPhone, no tiene cuenta ni servidor, y no usa anuncios, analítica ni rastreadores. La app es de código abierto, así que puedes leer exactamente qué hace con lo que escribes."),
        ("¿Cuánto cuesta?",
         "Nada, y no hay versión de pago. Una propina opcional pasa por la compra integrada de Apple y no desbloquea absolutamente nada. Todas las funciones están para todo el mundo, porque una herramienta de seguridad tras un muro de pago no lo es."),
        ("¿Me dice si algo es seguro?",
         "No, y nunca lo hará. El comprobador de riesgos enseña qué está documentado sobre una combinación, también con la medicación que tomas, y ahí se para. No hay luz verde. Para todo lo que importa, un médico o farmacéutico es el sitio correcto."),
        ("¿Cómo hago una copia de seguridad o cambio de teléfono?",
         "Activa la copia de iCloud en Ajustes para guardar una copia cifrada en tu propio iCloud Drive, o exporta tú mismo un archivo de copia cifrado. En un dispositivo nuevo, restaura desde iCloud o importa ese archivo durante la configuración."),
        ("¿Cómo bloqueo u oculto la app?",
         "En Ajustes, dentro de Privacidad y bloqueo, activa Face ID o pon un PIN. También puedes activar las notificaciones discretas para que la pantalla de bloqueo no revele nada, y ChillMate oculta su contenido en el selector de apps y durante grabaciones o duplicado de pantalla. Un toque deja la pantalla en negro."),
        ("¿Cómo borro mis datos?",
         "Entradas sueltas o todo de una vez, dentro de la app. Borrar la app elimina sus datos locales, y los de iCloud se quitan desde los ajustes de copia o desde iCloud. No hay ninguna copia en otro sitio por la que preguntar."),
        ("¿Qué países admite?",
         "ChillMate funciona en cualquier sitio. Los recursos de ayuda siguen al país que elijas en la configuración, con servicios integrados para los Países Bajos, Bélgica, Alemania, el Reino Unido, Irlanda, Francia, España, Estados Unidos y Australia, y alternativas internacionales en el resto."),
        ("¿Qué idiomas habla?",
         "Inglés, neerlandés, alemán, francés y español, en el teléfono y en el Apple Watch. Elige el idioma en la app o en los ajustes de iOS; vale el último que hayas cambiado."),
    ],
    "human": 'Soy una sola persona, en los Países Bajos. Hice la app que quería que existiera, y nunca veo nada de lo que tú metes en ella.',
    "footnotes": [
        'Sin red en ninguna parte de la app.',
        'La sincronización va a tu propia base privada.',
        'El PIN: 200.000 rondas PBKDF2, en el Llavero.',
        'Oculto en el selector de apps y durante grabaciones.',
        'Copias selladas con AES-GCM.',
        'Notificaciones que no revelan nada.',
        'Los resúmenes corren en el modelo en dispositivo de Apple.',
        'Las 30 combinaciones de arriba.',
        'El directorio de ayuda para 10 regiones.',
    ],
    "statement2_big": 'Nunca te dirá que algo es seguro.',
    "statement2_note": 'Ni el comprobador de riesgos, ni los resúmenes, en ningún sitio. Enseña lo que se sabe y te devuelve la decisión.',
    "nav_howto": 'Cómo funciona',
    "howto_title": 'ChillMate · Cómo funciona',
    "howto_desc": 'Una noche en tres momentos, qué se niega a hacer la app, todo lo que lleva dentro, y el Apple Watch.',
    "howto_h1": 'Cómo funciona',
    "howto_lede": 'Lo que no cabía en la portada: la forma de una noche, lo que no va a hacer, y qué lleva dentro de verdad.',
    "howto_back": 'Volver a la portada',
    "demo_meds_label": 'Lo que ya tomas',
    "demo_meds_ph": 'Nombre del medicamento, opcional',
    "demo_timing_label": 'Con cuánta separación',
    "demo_assess_label": 'Comprobaciones fijas',
    "demo_share": 'Copiar un enlace a esto',
    "demo_shared": 'Enlace copiado',
    "demo_print": 'Imprimir esto',
    "demo_meds_hit": 'Reconocido',
    "demo_meds_none": 'No se reconoció ningún grupo conocido.',
    "faq_teaser_indices": [0, 1, 2],

    "nav_chapters": [("who", "Para quién"), ("inside", "Por dentro"),
                     ("try", "Pruébalo"), ("privacy", "Privacidad"), ("specs", "Ficha técnica")],
    "scroll_cue": "Desplázate",

    "statement": [("0", "servidores"), ("0", "cuentas"), ("0", "rastreadores")],
    "statement_note": "No es una promesa. Es una arquitectura. Todo lo de abajo explica cómo, con enlace a la línea de código que lo demuestra.",

    "demo_eyebrow": "Pruébalo",
    "demo_h2": "Este es el comprobador de riesgos de verdad.",
    "demo_p": 'No una captura de él. Las mismas 30 combinaciones, las mismas palabras, funcionando aquí.',
    "demo_pick": "Elige qué hay en juego",
    "demo_none_title": "Nada documentado para esta combinación",
    "demo_none_body": "Eso no es lo mismo que seguro. Significa que esta tabla no tiene nada al respecto, y esta tabla no es la última palabra sobre nada.",
    "demo_empty": 'Elige algo, o escribe un medicamento, para ver qué diría la app.',
    "demo_reset": "Borrar",
    "demo_note": "Funciona entero en esta página. Nada de lo que toques aquí se envía a ningún sitio, por la misma razón que en la app.",
    "demo_try": "Probar GHB y alcohol",

    "specs_eyebrow": "Los detalles",
    "specs_h2": "Ficha técnica",
    "specs": [
        ("Requiere", "iPhone con iOS 26 o posterior"),
        ("Apple Watch", "App nativa, watchOS 26 o posterior"),
        ("Precio", "Gratis. Sin versión de pago, sin suscripción, sin anuncios."),
        ("Cuenta", "Ninguna. No hay nada que registrar."),
        ("Datos recogidos", "Ninguno"),
        ("Idiomas", "English, Nederlands, Deutsch, Français, Español"),
        ("Servicios de ayuda", "10 regiones, en el dispositivo, funciona sin conexión"),
        ("Combinaciones comprobadas", "30 interacciones documentadas, en el dispositivo"),
        ("Resúmenes escritos", "En el dispositivo, Apple Foundation Models"),
        ("Sync y copia", "Opcional, cifrado, tu propio iCloud"),
        ("Bloqueo", "Face ID, o un PIN derivado con 200.000 rondas PBKDF2"),
        ("Código", "Abierto, licencia MIT"),
        ("Versión", "4.2.1 (build 422)"),
    ],

    "footnotes_title": "Cada afirmación de esta página, y dónde comprobarla",
    "footnotes_intro": "Las páginas de marketing remiten sus afirmaciones a la letra pequeña. Esta las remite al código fuente.",
}
