# -*- coding: utf-8 -*-
"""German copy. Translated from lang_en.

"du", not "Sie", for the same reason the Dutch is "je": the app addresses you
informally, and a safety tool that switches to a formal register on the website
sounds like a different product than the one you install.
"""

S = {
    "skip": "Zum Inhalt springen",
    "nav_home": "Start",
    "nav_privacy": "Datenschutz",
    "nav_support": "Hilfe",
    "nav_about": "Über",
    "nav_github": "GitHub",
    "lang_label": "Sprache",
    "theme_dark": "Dunkel",
    "theme_light": "Hell",
    "theme_hint": "Farbschema wechseln",
    "to_top": "Nach oben",
    "made": "von einer Person in den Niederlanden gemacht",
    "copy": "Kopieren",
    "copied": "Kopiert",
    "call": "Anrufen:",
    "open": "Öffnen:",
    "policy_en_note": "Die Datenschutzerklärung gibt es auf Englisch und Niederländisch. Der englische Text ist maßgeblich.",

    "disclaimer": "ChillMate unterstützt Reflexion, Planung und dein Wohlbefinden. Es ersetzt keine Fachperson und entscheidet nie, ob etwas sicher ist. Wenn jemand in akuter Gefahr sein könnte, ruf den örtlichen Notruf.",

    "cat_emergency": "Notruf",
    "cat_crisis": "Krisen- und Suizidhilfe",
    "cat_sexual_health": "Sexuelle Gesundheit und STI-Tests",
    "cat_gp": "Deine Ärztin oder dein Arzt",
    "cat_drugs": "Drogeninfo und Harm Reduction",
    "cat_assault": "Nach sexualisierter Gewalt",
    "cat_lgbtq": "LGBTQ+ Unterstützung",
    "cat_emergency_d": "Akute Gefahr, Bewusstlosigkeit oder jemand, der nicht aufwacht.",
    "cat_crisis_d": "Kostenlos und vertraulich, wenn du dir etwas antun könntest oder dich nicht sicher fühlst.",
    "cat_sexual_health_d": "STI-Tests, PrEP, PEP-Fragen, Impfungen und sexuelle Gesundheit.",
    "cat_gp_d": "Wechselwirkungen, Schlaf, psychische Gesundheit, Substanzgebrauch und Überweisungen.",
    "cat_drugs_d": "Verlässliche, wertungsfreie Drogeninformation und Harm Reduction.",
    "cat_assault_d": "Unterstützung nach Gewalt, Nötigung oder Zweifeln an Einvernehmlichkeit.",
    "cat_lgbtq_d": "Ein offenes Ohr, Information und Weitervermittlung.",
    "cat_generic_local": "Frag bei deiner örtlichen Gesundheitsstelle nach.",

    "home_title": "ChillMate · Ein ruhiger, privater Ort, um auf dich zu achten",
    "home_desc": "Eine private Übersicht über deine Nächte, Pläne, Erinnerungen und Sicherheitswerkzeuge, komplett auf deinem iPhone. Kostenlos, Open Source, ohne Konto und ohne Server.",

    "h1": "Ein ruhiger, privater Ort, um auf dich zu achten.",
    # Short enough to survive a 1200x630 share card.
    "og_sub": "Kein Konto. Keine Server. Alles bleibt auf deinem iPhone.",
    "og_foot": "Open Source · iPhone und Apple Watch",
    "lede": 'Deine Nächte, Pläne und Sicherheitswerkzeuge in einer privaten Übersicht auf deinem iPhone. Kostenlos, Open Source, und ohne Server.',
    "cta_notify": "Sag mir Bescheid, wenn es da ist",
    "cta_see": "So funktioniert es",
    "status_note": "Noch nicht im App Store. Schick eine leere Mail und du hörst genau einmal von mir, an dem Tag, an dem es so weit ist.",
    "notify_subject": "Sag mir Bescheid, wenn ChillMate da ist",
    "notify_body": "Du musst nichts schreiben. Ich antworte einmal, am Tag des Starts, und lösche deine Adresse danach.",

    "audience_eyebrow": "Für wen es ist",
    "audience_h2": "Gemacht für die Nächte, um die es hier wirklich geht",
    "audience_p": 'Chems, Hookups, oder beides. ChillMate hat dazu keine Meinung und wird dich nie bitten, eine Nacht zu rechtfertigen.',
    "audience_points": [
        "Ein Risikocheck, der weiß, was du ohnehin nimmst, dein eigenes Rezept eingeschlossen.",
        "Ein Check-in-Timer, damit jemand weiß, dass du zu Hause bist, ohne dass du schreiben musst.",
        "Ein PEP-Fenster, das in dem Moment zu zählen beginnt, in dem es zählen könnte.",
        "Test-Erinnerungen, die auf dem Sperrbildschirm nie sagen, worum es geht.",
    ],
    "audience_chill": "Die App nennt eine Nacht einen <strong>Chill</strong>. Deinen, wie er auch war.",

    "walk_eyebrow": "Ein Blick hinein",
    "walk_h2": "Fünf Screens, und wofür sie da sind.",
    "walk": [
        ('Es ordnet sich selbst', 'Was aus heute Nacht auch wurde', 'Trag eine Nacht ein und der Startbildschirm ordnet sich darum herum. Hier hat er erkannt, dass ein PEP-Gespräch sinnvoll sein könnte, und den Countdown allein nach oben gestellt.'),
        ('Es sagt, was bekannt ist', 'Und weigert sich zu sagen, es sei sicher', 'Wähl aus, was im Spiel ist, deine Medikamente eingeschlossen, und es zeigt, was zu dieser Kombination dokumentiert ist. Es gibt kein grünes Licht.'),
        ('Ein Raum mit gedämpftem Licht', 'Für den Moment, in dem es schon schiefgeht', 'Wenig Reize, eins nach dem anderen. Atme, geh die Grounding-Schritte durch, und ruf erst jemanden an, wenn du das willst.'),
        ('Echte Anlaufstellen, offline', 'Hilfe von Menschen, nicht von einer App', 'Krisentelefone, sexuelle Gesundheit, Drogen und LGBTQ+ Unterstützung für das Land, das du einstellst. Eine Liste auf dem Handy, also auch ohne Empfang.'),
        ('Eine ehrliche Karte deiner Daten', 'In der App, nicht nur in einer Erklärung', 'Was auf dem Gerät liegt, was in einem verschlüsselten Backup wäre, und was ChillMate nie sendet. Dafür solltest du keine Erklärung lesen müssen.'),
    ],

    "night_eyebrow": "Wie es passt",
    "night_h2": "Eine Nacht, in drei Momenten.",
    "night": [
        ('Bevor du losgehst', 'Entscheide, solange es leicht ist', 'Lass die Kombination vom Risikocheck ansehen, halt fest, worauf du Lust hast, und starte einen Check-in-Timer. Fünf Minuten, solange du klar bist.'),
        ('Wenn du unterwegs bist', 'Ein Tipp, nichts tippen', 'Der Timer fragt, ob alles gut ist. Hilfe holen kennt deine Vertrauensperson und die richtige Notrufnummer für deinen Ort bereits. Deine Uhr kann für dich antworten.'),
        ('Der Morgen danach', 'Erinnere dich richtig', 'Schlaf, wie es dir geht, was tatsächlich geholfen hat. Eine Minute jetzt ist der Teil, über den du in drei Monaten froh bist.'),
    ],

    "features_eyebrow": "Was drin ist",
    "features": [
        ("book", "tint-blue", "Privates Log",
         "Halte eine Nacht so fest, wie du sie erinnern willst: Schlaf, wie es dir ging, und was danach geholfen hat."),
        ("chart", "tint-mint", "Deine Muster",
         "Ansichten über 30 und 90 Tage, was sich wirklich ändert, und ein Tageswert, den nur du je siehst."),
        ("life", "tint-purple", "Care-Werkzeuge",
         "Atmung, eine Pause bei Verlangen, ein Plan für eine sicherere Session, und ein Weg nach Hause, wenn du ihn willst."),
        ("flask", "tint-pink", "Risikocheck",
         "Hinweise in klarer Sprache zu Kombinationen, auch mit den Medikamenten, die du bereits nimmst."),
        ("bell", "tint-amber", "Erinnerungen, die passen",
         "Check-in-Timer, ein PEP-Fenster und Test-Erinnerungen, auf Wunsch diskret formuliert."),
        ("watch", "tint-blue", "An deinem Handgelenk",
         "Timer, Check-ins und eine Notrufnummer auf der Apple Watch, ohne zum Handy zu greifen."),
    ],

    "foryou_eyebrow": "Ist das etwas für dich",
    "foryou_h2": "Daran merkst du es.",
    "foryou": [
        "Du willst dich an letzte Nacht genau erinnern, nicht vage, und nicht über jemand anderen.",
        "Du nimmst PrEP und möchtest lieber nicht, dass die Erinnerung PrEP auf deinen Sperrbildschirm schreibt.",
        "Du willst einen Anlass, dich bei jemandem zu melden, der kein ganzes Gespräch ist.",
        "Du hast dich unter der Woche schon gefragt, ob es öfter ist als früher.",
        "Du willst die Notrufnummer für den Ort, an dem du bist, ohne einen Browser zu entsperren.",
    ],
    "foryou_not": "Wahrscheinlich nichts für dich, wenn du etwas suchst, das die Nacht für dich bewertet, dein Verhalten benotet oder dir sagt, eine Kombination sei sicher. Alle drei lässt es absichtlich."

                  ,
    "privacy_eyebrow": "Privat gebaut",
    "privacy_h2": "Dein Handy, und sonst nirgends",
    "privacy_intro": 'Datenschutz ist hier keine Einstellung. Es ist die Form der App.',
    "privacy_checks": [
        'Sichere sie mit Face ID oder PIN, alles auf dem Gerät verschlüsselt.',
        'Backups sind optional und verschlüsselt und gehen in deine eigene iCloud Drive.',
        'Mitteilungen können auf dem Sperrbildschirm bewusst vage bleiben.',
    ],
    "privacy_link": "Vollständige Datenschutzerklärung lesen",

    "proof_eyebrow": "Prüf es selbst",
    "proof_h2": "Glaub mir nicht einfach so",
    "proof_p": 'ChillMate ist Open Source. Jede Zeile, die deine Daten berührt, ist öffentlich, und das macht aus dem Versprechen oben etwas Prüfbares.',
    "proof_fact": 'Im Code der App gibt es keinen einzigen Netzwerkaufruf. Kein Analytics-SDK, kein Crash-Reporter, nirgends eine <code>URLSession</code>. Dein Handy verlässt nur, was du antippst.',
    "proof_cta_repo": "Quellcode lesen",
    "proof_cta_store": "Wo deine Daten liegen",
    "proof_caption": "Geprüft an ChillMate 4.2.1 (Build 422).",

    "diagram_title": "Wohin deine Daten gehen",
    "diagram_you": "Du",
    "diagram_phone": "Dein iPhone",
    "diagram_icloud": "Deine iCloud",
    "diagram_optional": "optional, verschlüsselt",
    "diagram_server": "Meine Server",
    "diagram_none": "gibt es nicht",

    "refuse_eyebrow": "Mit Absicht",
    "refuse_h2": "Was es nicht tut",
    "refuse_p": "Die meiste Arbeit steckt in dem, was es nicht tut. Das ist schwerer zu halten als Funktionen, denn jedes davon ist etwas, worum irgendwann jemand bittet.",
    "refuse": [
        ("Es sagt nicht, dass etwas sicher ist.", "Es zeigt, was zu einer Kombination dokumentiert ist, und gibt dir die Entscheidung zurück, denn es kennt deinen Körper, deine Dosis und deine Nacht nicht."),
        ("Es benotet dich nicht als Person.", "Es gibt eine Zahl für den Tag, sie bleibt auf deinem Handy, und nichts wird damit freigeschaltet oder vorenthalten."),
        ("Es nervt nicht.", "Jede Erinnerung ist aus, bis du sie einschaltest, und lässt sich so formulieren, dass ein Sperrbildschirm nichts verrät."),
        ("Es will kein Konto.", "Dazu gehörte ein Server, und ein Server ist eine Kopie von dir an einem Ort, an den du nicht kommst."),
        ("Es lässt dich nicht zahlen.", "Alles kostenlos. Das Trinkgeld schaltet nichts frei, denn ein Sicherheitswerkzeug hinter einer Bezahlschranke ist keines."),
    ],

    "watch_h3": "Es funktioniert, während das Handy in der Tasche bleibt",
    "watch_p": "Dosis-Timer, Trinken, diskrete Check-ins, eine Atemübung und ein Tipp zu deiner Vertrauensperson oder der örtlichen Notrufnummer, alles auf der Apple Watch, dazu Komplikationen für Zifferblatt und Smart Stack.",
    "watch_quote": "Wenn sich etwas falsch anfühlt, hol Hilfe. Du bist nicht in Schwierigkeiten.",
    "watch_quote_note": "Der gesamte Sicherheits-Screen der Uhr, Wortlaut inklusive.",
    "langs_h3": "Es funktioniert in deiner Sprache",
    "langs_p": "App und Website gibt es auf Englisch, Niederländisch, Deutsch, Französisch und Spanisch. Die Hilfsangebote richten sich nach dem Land, das du einstellst, nicht nach deiner Lesesprache, denn das sind zwei verschiedene Fragen.",

    "faq_teaser_eyebrow": "Bevor du fragst",
    "faq_teaser_h2": "Die drei Fragen, die alle stellen.",
    "faq_teaser_link": "Die übrigen Fragen, und echte Anlaufstellen",

    "support_title": "ChillMate · Hilfe und Unterstützung",
    "support_desc": "Krisentelefone und Gesundheitsangebote für dein Land, offline und druckbar, dazu häufige Fragen und wie du mich erreichst.",
    "support_h1": "Hilfe, und wie du mich erreichst",
    "support_lede": "Zuerst echte Anlaufstellen, denn dafür ist diese Seite am nützlichsten. Fragen zur App stehen weiter unten, und es liest eine einzelne Person jede Nachricht.",
    "support_urgent": "<strong>Warte im Notfall nicht auf die App.</strong> Wenn du oder jemand anderes in akuter Gefahr sein könnte, ruf jetzt den örtlichen Notruf.",
    "support_contact_eyebrow": "Kontakt aufnehmen",
    "support_contact_h2": "Kontakt",
    "support_contact_p": "Schreib an {email}. Eine Antwort dauert meist ein paar Tage. Deine iOS-Version und was du gerade getan hast, helfen sehr.",
    "support_email_btn": "Schreib mir",
    "support_issue_btn": "Problem melden",
    "support_faq_eyebrow": "Häufige Fragen",
    "support_help_eyebrow": "Echte Anlaufstellen",
    "support_help_h2": "Hilfe von Menschen, nicht von einer App",
    "support_help_p": "ChillMate ist kein Krisendienst. Wähl aus, wo du bist, dann helfen dir diese Stellen direkt. Diese Seite lässt sich drucken und funktioniert ohne Empfang, denn genau dann zählen diese Nummern.",
    "support_country_label": "Wo bist du?",
    "support_emergency_is": "Notruf hier:",
    "support_emergency_local": "dein örtlicher Notruf",
    "support_print": "Diese Seite drucken",

    "faq": [
        ("Sind meine Daten privat?",
         "Ja, und du musst mir nicht glauben. ChillMate hält alles auf deinem iPhone, hat kein Konto und keinen Server und betreibt keine Werbung, Analytics oder Tracker. Die App ist Open Source, du kannst also genau nachlesen, was mit deinen Eingaben passiert."),
        ("Was kostet es?",
         "Nichts, und es gibt keine bezahlte Version. Ein optionales Trinkgeld läuft über Apples In-App-Kauf und schaltet überhaupt nichts frei. Jede Funktion steht allen offen, denn ein Sicherheitswerkzeug hinter einer Bezahlschranke ist keines."),
        ("Sagt es mir, ob etwas sicher ist?",
         "Nein, und das wird es nie. Der Risikocheck zeigt, was zu einer Kombination dokumentiert ist, auch mit Medikamenten, die du nimmst, und hört da auf. Es gibt kein grünes Licht. Für alles Wichtige sind Ärztin oder Apotheke die richtige Stelle."),
        ("Wie mache ich ein Backup oder wechsle das Handy?",
         "Aktiviere iCloud-Backup in den Einstellungen, um ein verschlüsseltes Backup in deiner eigenen iCloud Drive zu speichern, oder exportiere selbst eine verschlüsselte Backup-Datei. Auf einem neuen Gerät stellst du beim Einrichten aus iCloud wieder her oder importierst die Datei."),
        ("Wie sperre oder verstecke ich die App?",
         "Aktiviere in den Einstellungen unter Datenschutz und Sperre Face ID oder setze eine PIN. Du kannst auch diskrete Mitteilungen einschalten, damit der Sperrbildschirm nichts verrät, und ChillMate verbirgt seinen Inhalt im App-Umschalter sowie bei Bildschirmaufnahme oder Spiegelung. Ein Tipp macht den Bildschirm schwarz."),
        ("Wie lösche ich meine Daten?",
         "Einzelne Einträge oder alles auf einmal, in der App. Die App zu löschen entfernt die lokalen Daten, iCloud-Daten entfernst du über die Backup-Einstellungen oder über iCloud. Es gibt nirgends sonst eine Kopie, nach der du fragen müsstest."),
        ("Welche Länder werden unterstützt?",
         "ChillMate funktioniert überall. Die Hilfsangebote richten sich nach dem Land, das du beim Einrichten wählst, mit eingebauten Angeboten für die Niederlande, Belgien, Deutschland, das Vereinigte Königreich, Irland, Frankreich, Spanien, die USA und Australien, und internationalen Alternativen überall sonst."),
        ("Welche Sprachen spricht es?",
         "Englisch, Niederländisch, Deutsch, Französisch und Spanisch, auf dem Handy und auf der Apple Watch. Stell die Sprache in der App oder in den iOS-Einstellungen ein; es gilt die zuletzt geänderte."),
    ],
    "human": 'Ich bin eine Person in den Niederlanden. Ich habe die App gebaut, die es geben sollte, und ich sehe nie etwas von dem, was du hineinschreibst.',
    "footnotes": [
        'Nirgends in der App Netzwerkverkehr.',
        'Sync geht in deine eigene private Datenbank.',
        'Die PIN: 200.000 PBKDF2-Runden, im Schlüsselbund.',
        'Verborgen im App-Umschalter und bei Bildschirmaufnahme.',
        'Backups mit AES-GCM versiegelt.',
        'Mitteilungstexte, die nichts verraten.',
        'Zusammenfassungen laufen auf Apples Modell im Gerät.',
        'Die 30 Kombinationen oben.',
        'Das Hilfeverzeichnis für 10 Regionen.',
    ],
    "statement2_big": 'Es sagt dir nie, dass etwas sicher ist.',
    "statement2_note": 'Nicht der Risikocheck, nicht die Zusammenfassungen, nirgends. Es zeigt, was bekannt ist, und gibt dir die Entscheidung zurück.',
    "nav_howto": 'So funktioniert es',
    "howto_title": 'ChillMate · So funktioniert es',
    "howto_desc": 'Eine Nacht in drei Momenten, was die App nicht tut, was drin ist, und die Apple Watch.',
    "howto_h1": 'So funktioniert es',
    "howto_lede": 'Die Teile, die vorne keinen Platz hatten: die Form einer Nacht, was es nicht tut, und was wirklich drin ist.',
    "howto_back": 'Zurück zur Startseite',
    "demo_meds_label": 'Was du ohnehin nimmst',
    "demo_meds_ph": 'Name des Medikaments, optional',
    "demo_timing_label": 'Wie dicht beieinander',
    "demo_assess_label": 'Ständige Checks',
    "demo_share": 'Link dazu kopieren',
    "demo_shared": 'Link kopiert',
    "demo_print": 'Das drucken',
    "demo_meds_hit": 'Erkannt',
    "demo_meds_none": 'Keine bekannte Gruppe erkannt.',
    "faq_teaser_indices": [0, 1, 2],

    "nav_chapters": [("who", "Für wen"), ("inside", "Blick hinein"),
                     ("try", "Ausprobieren"), ("privacy", "Datenschutz"), ("specs", "Technische Daten")],
    "scroll_cue": "Scrollen",

    "statement": [("0", "Server"), ("0", "Konten"), ("0", "Tracker")],
    "statement_note": "Kein Versprechen. Eine Bauweise. Alles hier drunter erklärt wie, mit Link auf die Zeile Code, die es belegt.",

    "demo_eyebrow": "Ausprobieren",
    "demo_h2": "Das ist der echte Risikocheck.",
    "demo_p": 'Kein Screenshot davon. Dieselben 30 Kombinationen, derselbe Wortlaut, hier ausgeführt.',
    "demo_pick": "Wähl, was im Spiel ist",
    "demo_none_title": "Zu dieser Kombination ist nichts dokumentiert",
    "demo_none_body": "Das ist nicht dasselbe wie sicher. Es heißt, diese Tabelle hat nichts dazu, und diese Tabelle ist zu nichts das letzte Wort.",
    "demo_empty": 'Wähl etwas aus oder tipp ein Medikament ein, um zu sehen, was die App sagen würde.',
    "demo_reset": "Zurücksetzen",
    "demo_note": "Läuft vollständig auf dieser Seite. Was du hier antippst, geht nirgendwohin, aus demselben Grund wie in der App.",
    "demo_try": "GHB und Alkohol ausprobieren",

    "specs_eyebrow": "Die Details",
    "specs_h2": "Technische Daten",
    "specs": [
        ("Voraussetzung", "iPhone mit iOS 26 oder neuer"),
        ("Apple Watch", "Eigene App, watchOS 26 oder neuer"),
        ("Preis", "Kostenlos. Keine bezahlte Stufe, kein Abo, keine Werbung."),
        ("Konto", "Keins. Es gibt nichts zu registrieren."),
        ("Erhobene Daten", "Keine"),
        ("Sprachen", "English, Nederlands, Deutsch, Français, Español"),
        ("Hilfsangebote", "10 Regionen, auf dem Gerät, funktioniert offline"),
        ("Geprüfte Kombinationen", "30 dokumentierte Wechselwirkungen, auf dem Gerät"),
        ("Geschriebene Zusammenfassungen", "Auf dem Gerät, Apple Foundation Models"),
        ("Sync und Backup", "Optional, verschlüsselt, deine eigene iCloud"),
        ("Sperre", "Face ID, oder eine PIN mit 200.000 PBKDF2-Runden"),
        ("Quellcode", "Offen, MIT-Lizenz"),
        ("Version", "4.2.1 (Build 422)"),
    ],

    "footnotes_title": "Jede Behauptung auf dieser Seite, und wo du sie prüfst",
    "footnotes_intro": "Marketingseiten fußnoten ihre Behauptungen ins Kleingedruckte. Diese fußnotet sie in den Quellcode.",
}
