# -*- coding: utf-8 -*-
"""French copy. Translated from lang_en.

"vous", unlike the Dutch and German files, because a stranger addressing a
French reader as "tu" on a first visit reads as presumptuous rather than warm,
which is the opposite of the effect the informal register has in nl and de.
"""

S = {
    "skip": "Aller au contenu",
    "nav_home": "Accueil",
    "nav_privacy": "Confidentialité",
    "nav_support": "Aide",
    "nav_about": "À propos",
    "nav_github": "GitHub",
    "lang_label": "Langue",
    "theme_dark": "Sombre",
    "theme_light": "Clair",
    "theme_hint": "Changer de thème",
    "to_top": "Retour en haut",
    "made": "fait par une seule personne aux Pays-Bas",
    "copy": "Copier",
    "copied": "Copié",
    "call": "Appeler",
    "open": "Ouvrir",
    "policy_en_note": "La politique de confidentialité existe en anglais et en néerlandais. Le texte anglais fait foi.",

    "disclaimer": "ChillMate accompagne la réflexion, la planification et votre bien-être. Il ne remplace pas un professionnel et ne décide jamais si quelque chose est sûr. Si une personne peut être en danger immédiat, appelez votre numéro d'urgence local.",

    "cat_emergency": "Secours d'urgence",
    "cat_crisis": "Crise et prévention du suicide",
    "cat_sexual_health": "Santé sexuelle et dépistage IST",
    "cat_gp": "Votre médecin",
    "cat_drugs": "Information drogues et réduction des risques",
    "cat_assault": "Après une agression sexuelle",
    "cat_lgbtq": "Soutien LGBTQ+",
    "cat_emergency_d": "Danger immédiat, perte de connaissance, ou une personne qu'on ne parvient pas à réveiller.",
    "cat_crisis_d": "Gratuit et confidentiel, si vous risquez de vous faire du mal ou ne vous sentez pas en sécurité.",
    "cat_sexual_health_d": "Dépistage IST, PrEP, questions PEP, vaccination et santé sexuelle.",
    "cat_gp_d": "Interactions médicamenteuses, sommeil, santé mentale, consommation et orientation.",
    "cat_drugs_d": "Information fiable et sans jugement, et réduction des risques.",
    "cat_assault_d": "Soutien après une agression, une contrainte ou un doute sur le consentement.",
    "cat_lgbtq_d": "Une écoute, de l'information et une orientation.",
    "cat_generic_local": "Renseignez-vous auprès de votre service de santé local.",

    "home_title": "ChillMate · Un endroit calme et privé pour prendre soin de vous",
    "home_desc": "Un aperçu privé de vos nuits, plans, rappels et outils de sécurité, entièrement sur votre iPhone. Gratuit, open source, sans compte et sans serveur.",

    "h1": "Un endroit calme et privé pour prendre soin de vous.",
    # Short enough to survive a 1200x630 share card.
    "og_sub": "Sans compte. Sans serveur. Tout reste sur votre iPhone.",
    "og_foot": "Open source · iPhone et Apple Watch",
    "lede": "ChillMate réunit vos nuits, vos plans, vos rappels et vos outils de sécurité dans un aperçu privé sur votre iPhone. C'est gratuit, c'est open source, et il n'y a pas de serveur, donc rien de tout cela n'existe ailleurs.",
    "cta_notify": "Prévenez-moi à la sortie",
    "cta_see": "Voir comment ça marche",
    "status_note": "Pas encore sur l'App Store. Envoyez un e-mail vide et vous aurez de mes nouvelles une seule fois, le jour de la sortie.",
    "notify_subject": "Prévenez-moi quand ChillMate sort",
    "notify_body": "Rien à écrire. Je réponds une fois, le jour du lancement, puis je supprime votre adresse.",

    "audience_eyebrow": "À qui ça s'adresse",
    "audience_h2": "Fait pour les nuits dont il s'agit vraiment",
    "audience_p": "Chems, plans cul, ou les deux. ChillMate n'a pas d'avis là-dessus et ne vous demandera jamais de justifier une soirée. Ce qu'il fait : garder les parties pratiques que vous préférez ne pas démêler à quatre heures du matin.",
    "audience_points": [
        "Un vérificateur de risques qui connaît ce que vous prenez déjà, votre ordonnance comprise.",
        "Un minuteur de check-in, pour que quelqu'un sache que vous êtes rentré sans avoir à écrire.",
        "Une fenêtre PEP qui commence à compter au moment où cela pourrait compter.",
        "Des rappels de dépistage qui ne disent jamais pourquoi sur votre écran verrouillé.",
    ],
    "audience_chill": "L'app appelle une soirée un <strong>Chill</strong>. La vôtre, quelle qu'elle ait été.",

    "walk_eyebrow": "Un aperçu",
    "walk_h2": "Cinq écrans, et à quoi chacun sert.",
    "walk": [
        ("Il se réorganise", "Quoi que soit devenue la nuit",
         "Notez une soirée et l'écran d'accueil se réorganise autour. Ici il a compris qu'une conversation PEP pourrait valoir la peine, et a placé le compte à rebours seul en haut. Obtenir de l'aide reste épinglé au-dessus de tout."),
        ("Il dit ce qui est connu", "Et refuse de dire que c'est sûr",
         "Indiquez ce qui est en jeu, y compris vos propres médicaments, et le vérificateur de risques vous montre ce qui est documenté sur cette association. Il n'y a pas de feu vert. Rien dans ChillMate ne vous dira jamais que quelque chose va bien."),
        ("Une pièce aux lumières baissées", "Pour quand ça va déjà mal",
         "Peu de stimulation, une chose à la fois. Lancez le minuteur de respiration, suivez les étapes d'ancrage, et n'appelez quelqu'un que si vous le décidez."),
        ("De vrais services, hors ligne", "De l'aide humaine, pas une application",
         "Lignes de crise, santé sexuelle, drogues, soutien LGBTQ+ et aide pratique pour le pays que vous indiquez. C'est une liste sur votre téléphone, donc elle marche sans réseau et sans rien chercher."),
        ("Une carte honnête de vos données", "Dans l'app, pas seulement dans une politique",
         "Ce qui est sur l'appareil, ce que contiendrait une sauvegarde chiffrée, les catégories Santé que vous avez autorisées, et ce que ChillMate n'envoie jamais. Vous ne devriez pas avoir à lire une politique pour le savoir."),
    ],

    "night_eyebrow": "Comment ça s'insère",
    "night_h2": "Une nuit, en trois temps.",
    "night": [
        ("Avant de sortir", "Décidez pendant que c'est facile",
         "Passez l'association au vérificateur de risques, posez ce dont vous avez envie et ce dont vous n'avez pas envie, et lancez un minuteur de check-in. Cinq minutes maintenant, pendant que vous êtes clair et que rien n'est arrivé."),
        ("Pendant la soirée", "Un geste, rien à écrire",
         "Le minuteur demande si ça va. Je vais bien, c'est un geste. Obtenir de l'aide, c'est l'autre, et il connaît déjà votre personne de confiance et le bon numéro d'urgence là où vous êtes. Votre montre peut répondre pour vous."),
        ("Le lendemain matin", "Souvenez-vous précisément",
         "Le sommeil, comment vous allez, ce qui a vraiment aidé. Cela prend une minute et c'est la partie dont vous serez content dans trois mois, quand ces tendances seront le seul relevé honnête que vous ayez."),
    ],

    "features_eyebrow": "Ce qu'il contient",
    "features": [
        ("book", "tint-blue", "Journal privé",
         "Notez une soirée comme vous voulez vous en souvenir : sommeil, ressenti, et ce qui a aidé ensuite."),
        ("chart", "tint-mint", "Vos tendances",
         "Des vues sur 30 et 90 jours de ce qui change vraiment, et une note du jour que vous seul verrez."),
        ("life", "tint-purple", "Outils de soin",
         "Respiration, pause face à l'envie, plan pour une session plus sûre, et un trajet de retour si vous le voulez."),
        ("flask", "tint-pink", "Vérificateur de risques",
         "Des mises en garde en langage clair sur les associations, y compris avec vos médicaments actuels."),
        ("bell", "tint-amber", "Des rappels qui vous vont",
         "Minuteurs de check-in, fenêtre PEP et rappels de dépistage, formulés discrètement si vous préférez."),
        ("watch", "tint-blue", "À votre poignet",
         "Minuteurs, check-ins et un numéro d'urgence sur Apple Watch, sans sortir votre téléphone."),
    ],

    "foryou_eyebrow": "Est-ce pour vous",
    "foryou_h2": "Vous le saurez à ceci.",
    "foryou": [
        "Vous voulez vous souvenir précisément d'hier soir, pas vaguement, et pas par quelqu'un d'autre.",
        "Vous êtes sous PrEP et préféreriez que le rappel n'affiche pas PrEP sur votre écran verrouillé.",
        "Vous voulez une raison de donner signe de vie qui ne soit pas toute une conversation.",
        "Vous vous êtes demandé, en semaine, si c'était plus souvent qu'avant.",
        "Vous voulez le numéro d'urgence de là où vous êtes, sans déverrouiller un navigateur.",
    ],
    "foryou_not": "Ce n'est sans doute pas pour vous si vous cherchez quelque chose qui juge la soirée à votre place, note votre comportement, ou vous dit qu'une association est sûre. Il ne fait aucun des trois, volontairement.",

    "privacy_eyebrow": "Privé par conception",
    "privacy_h2": "Votre téléphone, et nulle part ailleurs",
    "privacy_intro": "Ici, la confidentialité n'est pas une option à activer. C'est la forme même de l'app.",
    "privacy_checks": [
        "Aucun compte, aucune inscription. Aucun serveur ne détient vos notes, parce qu'il n'y a pas de serveur.",
        "Pas de publicité, pas d'analytique, pas de traceurs, et rien n'est jamais vendu ni partagé.",
        "Verrouillez avec Face ID ou un code, tout étant chiffré sur l'appareil.",
        "Les sauvegardes sont facultatives et chiffrées, et vont dans votre propre iCloud Drive.",
        "Les notifications peuvent rester volontairement vagues sur l'écran verrouillé.",
    ],
    "privacy_link": "Lire la politique de confidentialité complète",

    "proof_eyebrow": "Vérifiez vous-même",
    "proof_h2": "Ne me croyez pas sur parole",
    "proof_p": "ChillMate est open source. Chaque ligne qui touche vos données est publique, ce qui transforme la promesse ci-dessus en quelque chose que vous pouvez vérifier plutôt qu'en quelque chose où il faut me faire confiance.",
    "proof_fact": "Le code de l'app ne contient aucun appel réseau. Aucun SDK d'analytique, aucun rapport de plantage, aucune <code>URLSession</code> nulle part. Seul ce que vous touchez quitte votre téléphone : un appel, un lien, un message que vous avez écrit.",
    "proof_cta_repo": "Lire le code source",
    "proof_cta_store": "Où vivent vos données",
    "proof_caption": "Vérifié sur ChillMate 4.2.1 (build 422).",

    "diagram_title": "Où vont vos données",
    "diagram_you": "Vous",
    "diagram_phone": "Votre iPhone",
    "diagram_icloud": "Votre iCloud",
    "diagram_optional": "facultatif, chiffré",
    "diagram_server": "Mes serveurs",
    "diagram_none": "il n'y en a pas",

    "refuse_eyebrow": "À dessein",
    "refuse_h2": "Ce qu'il ne fera pas",
    "refuse_p": "L'essentiel du travail est dans ce qu'il ne fait pas. C'est plus difficile à tenir que des fonctionnalités, car chacun de ces refus est une chose que quelqu'un finira par demander.",
    "refuse": [
        ("Il ne dira pas que quelque chose est sûr.", "Il montre ce qui est documenté sur une association et vous rend la décision, parce qu'il ne connaît ni votre corps, ni votre dose, ni votre soirée."),
        ("Il ne vous note pas en tant que personne.", "Il y a un chiffre pour la journée, il reste sur votre téléphone, et rien n'est débloqué ni retenu par lui."),
        ("Il ne harcèle pas.", "Chaque rappel est désactivé jusqu'à ce que vous l'activiez, et peut être formulé pour qu'un écran verrouillé ne révèle rien."),
        ("Il ne veut pas de compte.", "Cela impliquerait un serveur, et un serveur est une copie de vous à un endroit hors de votre portée."),
        ("Il ne vous fera pas payer.", "Tout est gratuit. Le pourboire ne débloque rien, car un outil de sécurité derrière un paywall n'en est pas un."),
    ],

    "watch_h3": "Il marche pendant que le téléphone reste dans la poche",
    "watch_p": "Minuteurs de dose, hydratation, check-ins discrets, un exercice de respiration et un geste vers votre personne de confiance ou le numéro d'urgence local, le tout sur Apple Watch, avec des complications pour le cadran et la Smart Stack.",
    "watch_quote": "Si quelque chose ne va pas, demandez de l'aide. Vous n'avez rien à vous reprocher.",
    "watch_quote_note": "Tout l'écran Sécurité de la montre, formulation comprise.",
    "langs_h3": "Il marche dans votre langue",
    "langs_p": "L'app et ce site existent en anglais, néerlandais, allemand, français et espagnol. Les ressources d'aide suivent le pays que vous indiquez, pas la langue que vous lisez, car ce sont deux questions différentes.",

    "faq_teaser_eyebrow": "Avant de demander",
    "faq_teaser_h2": "Les trois questions que tout le monde pose.",
    "faq_teaser_link": "Le reste des questions, et de vrais services d'aide",

    "support_title": "ChillMate · Aide et soutien",
    "support_desc": "Lignes de crise et services de santé pour votre pays, hors ligne et imprimables, plus les questions fréquentes et comment me joindre.",
    "support_h1": "De l'aide, et comment me joindre",
    "support_lede": "Les vrais services d'abord, car c'est à cela que cette page sert le mieux. Les questions sur l'app viennent ensuite, et une seule personne lit chaque message.",
    "support_urgent": "<strong>En cas d'urgence, n'attendez pas l'app.</strong> Si vous ou quelqu'un d'autre pouvez être en danger immédiat, appelez tout de suite votre numéro d'urgence local.",
    "support_contact_eyebrow": "Nous écrire",
    "support_contact_h2": "Contact",
    "support_contact_p": "Écrivez à {email}. La réponse prend en général quelques jours. Votre version d'iOS et ce que vous faisiez au moment du problème aident beaucoup.",
    "support_email_btn": "M'écrire",
    "support_issue_btn": "Signaler un problème",
    "support_faq_eyebrow": "Questions fréquentes",
    "support_help_eyebrow": "De vrais services",
    "support_help_h2": "De l'aide humaine, pas une application",
    "support_help_p": "ChillMate n'est pas un service de crise. Indiquez où vous êtes et ces organisations pourront vous aider directement. Cette page s'imprime et fonctionne sans réseau, car c'est exactement là que ces numéros comptent.",
    "support_country_label": "Où êtes-vous ?",
    "support_emergency_is": "Numéro d'urgence ici :",
    "support_emergency_local": "votre numéro d'urgence local",
    "support_print": "Imprimer cette page",

    "faq": [
        ("Mes données sont-elles privées ?",
         "Oui, et vous n'avez pas à me croire. ChillMate garde tout sur votre iPhone, n'a ni compte ni serveur, et n'utilise ni publicité, ni analytique, ni traceurs. L'app est open source, vous pouvez donc lire exactement ce qu'elle fait de ce que vous saisissez."),
        ("Combien ça coûte ?",
         "Rien, et il n'y a pas de version payante. Un pourboire facultatif passe par l'achat intégré Apple et ne débloque strictement rien. Toutes les fonctions sont là pour tout le monde, car un outil de sécurité derrière un paywall n'en est pas un."),
        ("Est-ce qu'il me dit si quelque chose est sûr ?",
         "Non, et il ne le fera jamais. Le vérificateur de risques montre ce qui est documenté sur une association, y compris avec vos médicaments, et s'arrête là. Il n'y a pas de feu vert. Pour tout ce qui compte, un médecin ou un pharmacien est le bon interlocuteur."),
        ("Comment sauvegarder, ou changer de téléphone ?",
         "Activez la sauvegarde iCloud dans les réglages pour enregistrer une sauvegarde chiffrée dans votre propre iCloud Drive, ou exportez vous-même un fichier de sauvegarde chiffré. Sur un nouvel appareil, restaurez depuis iCloud ou importez ce fichier pendant la configuration."),
        ("Comment verrouiller ou masquer l'app ?",
         "Dans les réglages, sous Confidentialité et verrouillage, activez Face ID ou définissez un code. Vous pouvez aussi activer les notifications discrètes pour que l'écran verrouillé ne révèle rien, et ChillMate masque son contenu dans le sélecteur d'apps ainsi que pendant un enregistrement ou une recopie d'écran. Un geste éteint l'écran."),
        ("Comment supprimer mes données ?",
         "Des entrées une par une ou tout d'un coup, dans l'app. Supprimer l'app efface ses données locales, et les données iCloud se retirent depuis les réglages de sauvegarde ou depuis iCloud. Il n'existe aucune copie ailleurs sur laquelle vous auriez à revenir."),
        ("Quels pays sont pris en charge ?",
         "ChillMate fonctionne partout. Les ressources d'aide suivent le pays choisi à la configuration, avec des services intégrés pour les Pays-Bas, la Belgique, l'Allemagne, le Royaume-Uni, l'Irlande, la France, l'Espagne, les États-Unis et l'Australie, et des solutions internationales ailleurs."),
        ("Quelles langues parle-t-il ?",
         "Anglais, néerlandais, allemand, français et espagnol, sur le téléphone et sur Apple Watch. Réglez la langue dans l'app ou dans les réglages iOS ; c'est le dernier changement qui s'applique."),
    ],
    "faq_teaser_indices": [0, 1, 2],
}
