# -*- coding: utf-8 -*-
"""Content for the ChillMate site, in every language the app itself ships.

The app speaks English, Dutch, German, French and Spanish. A site that only
speaks English sends most of its readers to a page they have to translate
themselves, which is the wrong first impression for an app whose whole promise
is that it is easy to reach when you are not at your best.

The privacy policy is deliberately English only. It is the document that says
what happens to someone's data, and five translations of it would be five
documents to keep in step. One authoritative text is safer than five drifting
ones, and every localised page links to it plainly.
"""

# Order matters: this is the order of the language menu.
LANGS = ["en", "nl", "de", "fr", "es"]

LANG_NAMES = {
    "en": "English",
    "nl": "Nederlands",
    "de": "Deutsch",
    "fr": "Français",
    "es": "Español",
}

# BCP-47 tags for <html lang> and hreflang.
LANG_TAGS = {
    "en": "en",
    "nl": "nl",
    "de": "de",
    "fr": "fr",
    "es": "es",
}


# --------------------------------------------------------------------------
# Help services, mirroring ChillMate/SupportDirectoryViews.swift
# --------------------------------------------------------------------------
#
# One list per country, each entry a (category, name, url) triple. The action
# label is derived from the url rather than written out, so adding a country
# adds no new strings to translate.

CATEGORIES = ["emergency", "crisis", "sexual_health", "gp", "drugs", "assault", "lgbtq"]

COUNTRIES = {
    "NL": {
        "emergency": "112",
        "items": [
            ("emergency", "112", "tel:112"),
            ("crisis", "113 Zelfmoordpreventie", "https://www.113.nl"),
            ("sexual_health", "GGD", "https://www.ggd.nl"),
            ("gp", "Huisarts", None),
            ("drugs", "Drugs Infolijn", "https://www.drugsinfo.nl"),
            ("assault", "Centrum Seksueel Geweld", "https://centrumseksueelgeweld.nl"),
            ("lgbtq", "Switchboard LGBT+", "https://switchboard.nl"),
        ],
    },
    "BE": {
        "emergency": "112",
        "items": [
            ("emergency", "112", "tel:112"),
            ("crisis", "Zelfmoordlijn 1813", "tel:1813"),
            ("sexual_health", "Sensoa", "https://www.sensoa.be"),
            ("gp", "Huisarts", None),
            ("drugs", "De DrugLijn", "https://www.druglijn.be"),
            ("assault", "Zorgcentra na Seksueel Geweld", "https://www.seksueelgeweld.be"),
            ("lgbtq", "Lumi", "https://lumi.be"),
        ],
    },
    "DE": {
        "emergency": "112",
        "items": [
            ("emergency", "112", "tel:112"),
            ("crisis", "TelefonSeelsorge", "tel:08001110111"),
            ("sexual_health", "Deutsche Aidshilfe", "https://www.aidshilfe.de"),
            ("gp", "Hausarzt", None),
            ("drugs", "drugcom.de", "https://www.drugcom.de"),
            ("assault", "Hilfetelefon", "tel:116016"),
            ("lgbtq", "LSVD+", "https://www.lsvd.de"),
        ],
    },
    "GB": {
        "emergency": "999",
        "items": [
            ("emergency", "999", "tel:999"),
            ("crisis", "Samaritans", "tel:116123"),
            ("sexual_health", "NHS sexual health", "https://www.nhs.uk/live-well/sexual-health/"),
            ("gp", "GP", None),
            ("drugs", "FRANK", "https://www.talktofrank.com"),
            ("assault", "Rape Crisis", "https://rapecrisis.org.uk"),
            ("lgbtq", "Switchboard LGBTQ+", "https://switchboard.lgbt"),
        ],
    },
    "FR": {
        "emergency": "112",
        "items": [
            ("emergency", "112", "tel:112"),
            ("crisis", "3114", "tel:3114"),
            ("sexual_health", "Sida Info Service", "https://www.sida-info-service.org"),
            ("gp", "Médecin traitant", None),
            ("drugs", "Drogues Info Service", "https://www.drogues-info-service.fr"),
            ("assault", "Viols Femmes Informations", "tel:0800059595"),
            ("lgbtq", "SOS homophobie", "https://www.sos-homophobie.org"),
        ],
    },
    "ES": {
        "emergency": "112",
        "items": [
            ("emergency", "112", "tel:112"),
            ("crisis", "024", "tel:024"),
            ("sexual_health", "Sanidad", "https://www.sanidad.gob.es"),
            ("gp", "Médico de cabecera", None),
            ("drugs", "Energy Control", "https://energycontrol.org"),
            ("assault", "016", "tel:016"),
            ("lgbtq", "FELGTBI+", "https://felgtbi.org"),
        ],
    },
    "US": {
        "emergency": "911",
        "items": [
            ("emergency", "911", "tel:911"),
            ("crisis", "988 Suicide & Crisis Lifeline", "tel:988"),
            ("sexual_health", "CDC GetTested", "https://gettested.cdc.gov"),
            ("gp", "Primary care doctor", None),
            ("drugs", "DanceSafe", "https://dancesafe.org"),
            ("assault", "RAINN", "https://www.rainn.org"),
            ("lgbtq", "The Trevor Project", "https://www.thetrevorproject.org"),
        ],
    },
    "IE": {
        "emergency": "112",
        "items": [
            ("emergency", "112", "tel:112"),
            ("crisis", "Samaritans", "tel:116123"),
            ("sexual_health", "Sexual Wellbeing (HSE)", "https://www.sexualwellbeing.ie"),
            ("gp", "GP", None),
            ("drugs", "Drugs.ie", "https://www.drugs.ie"),
            ("assault", "Dublin Rape Crisis Centre", "https://www.drcc.ie"),
            ("lgbtq", "LGBT Ireland", "https://lgbt.ie"),
        ],
    },
    "AU": {
        "emergency": "000",
        "items": [
            ("emergency", "000", "tel:000"),
            ("crisis", "Lifeline", "tel:131114"),
            ("sexual_health", "Healthdirect", "https://www.healthdirect.gov.au/sexual-health"),
            ("gp", "GP", None),
            ("drugs", "Alcohol and Drug Foundation", "https://adf.org.au"),
            ("assault", "1800RESPECT", "tel:1800737732"),
            ("lgbtq", "QLife", "https://qlife.org.au"),
        ],
    },
    "XX": {
        "emergency": None,
        "items": [
            ("emergency", None, None),
            ("crisis", "Find a Helpline", "https://findahelpline.com"),
            ("sexual_health", None, None),
            ("gp", None, None),
            ("drugs", "TripSit", "https://tripsit.me"),
            ("assault", None, None),
            ("lgbtq", None, None),
        ],
    },
}

# The order countries appear in the picker. "XX" is the anywhere-else fallback
# and always sits last.
COUNTRY_ORDER = ["NL", "BE", "DE", "GB", "IE", "FR", "ES", "US", "AU", "XX"]


COUNTRY_NAMES = {
    "en": {"NL": "Netherlands", "BE": "Belgium", "DE": "Germany", "GB": "United Kingdom",
           "IE": "Ireland", "FR": "France", "ES": "Spain", "US": "United States",
           "AU": "Australia", "XX": "Somewhere else"},
    "nl": {"NL": "Nederland", "BE": "België", "DE": "Duitsland", "GB": "Verenigd Koninkrijk",
           "IE": "Ierland", "FR": "Frankrijk", "ES": "Spanje", "US": "Verenigde Staten",
           "AU": "Australië", "XX": "Ergens anders"},
    "de": {"NL": "Niederlande", "BE": "Belgien", "DE": "Deutschland", "GB": "Vereinigtes Königreich",
           "IE": "Irland", "FR": "Frankreich", "ES": "Spanien", "US": "Vereinigte Staaten",
           "AU": "Australien", "XX": "Anderswo"},
    "fr": {"NL": "Pays-Bas", "BE": "Belgique", "DE": "Allemagne", "GB": "Royaume-Uni",
           "IE": "Irlande", "FR": "France", "ES": "Espagne", "US": "États-Unis",
           "AU": "Australie", "XX": "Ailleurs"},
    "es": {"NL": "Países Bajos", "BE": "Bélgica", "DE": "Alemania", "GB": "Reino Unido",
           "IE": "Irlanda", "FR": "Francia", "ES": "España", "US": "Estados Unidos",
           "AU": "Australia", "XX": "En otro lugar"},
}


# --------------------------------------------------------------------------
# User-visible strings
# --------------------------------------------------------------------------

STRINGS = {}

STRINGS["en"] = {
    # chrome
    "skip": "Skip to content",
    "nav_home": "Home",
    "nav_privacy": "Privacy",
    "nav_support": "Support",
    "nav_about": "About",
    "nav_github": "GitHub",
    "lang_label": "Language",
    "theme_dark": "Dark",
    "theme_light": "Light",
    "theme_hint": "Switch colour theme",
    "to_top": "Back to top",
    "made": "made with care in the Netherlands",
    "copy": "Copy",
    "copied": "Copied",
    "call": "Call",
    "open": "Open",
    "policy_en_note": "The privacy policy is kept in English only, so there is one authoritative text rather than five that can drift apart.",

    # categories
    "cat_emergency": "Emergency services",
    "cat_crisis": "Crisis and suicide support",
    "cat_sexual_health": "Sexual health and STI testing",
    "cat_gp": "Your doctor",
    "cat_drugs": "Drug information and harm reduction",
    "cat_assault": "After sexual assault",
    "cat_lgbtq": "LGBTQ+ support",
    "cat_emergency_d": "Immediate danger, unconsciousness, or someone who cannot be woken.",
    "cat_crisis_d": "Free and confidential, if you might hurt yourself or cannot stay safe.",
    "cat_sexual_health_d": "STI testing, PrEP, PEP questions, vaccination, and sexual health support.",
    "cat_gp_d": "Medication interactions, sleep, mental health, substance use, and referrals.",
    "cat_drugs_d": "Trusted, non-judgemental drug information and harm reduction.",
    "cat_assault_d": "Support after assault, coercion, or a consent concern.",
    "cat_lgbtq_d": "A listening ear, information, and referral.",
    "cat_generic_local": "Ask your local health service.",

    # home
    "home_title": "ChillMate · A calm, private place to look after yourself",
    "home_desc": "ChillMate keeps your logs, plans, reminders and personal-safety tools in one private overview. Everything stays on your iPhone. No account, no ads, no tracking.",
    "h1": "A calm, private place to look after yourself.",
    "lede": "ChillMate keeps your logs, reflections, plans, reminders and personal-safety tools in one private overview. Everything stays on your iPhone. No account, no ads, no trackers, nothing sold.",
    "cta_support": "Support and help",
    "cta_privacy": "How privacy works",
    "status_note": "Not on the App Store yet. This page will link to it once it is.",

    "walk_eyebrow": "A look inside",
    "walk_h2": "Five screens, and what each one is for.",
    "walk": [
        ("Home", "Everything at a glance",
         "Your streak, your score, and the tools that fit this moment. Get help now stays pinned to the top, so breathing, grounding and an emergency call are never something you have to hunt for."),
        ("Panic support", "A room with the lights turned down",
         "A low-stimulation space for anxiety or feeling unwell. Start the breathing timer, work through grounding steps, and call someone only if you decide you want to."),
        ("Privacy dashboard", "A plain map of your own data",
         "What is stored on the device, what an encrypted backup would contain, which Health categories you allowed, and what ChillMate never sends. In the app, not just in a policy."),
        ("Support", "Real services, offline",
         "Crisis lines, sexual health, drugs, LGBTQ+ support and practical care for the country you set. It is a list on your phone, so it works with no signal and no lookup."),
        ("More", "Nothing buried",
         "Profile, settings, privacy, emergency card and support, in one searchable place instead of scattered through menus."),
    ],

    "features_eyebrow": "What it does",
    "features": [
        ("book", "tint-blue", "Private log",
         "Record a night the way you want to remember it: sleep, how you felt, and what helped afterwards."),
        ("chart", "tint-mint", "Your patterns",
         "Thirty and ninety day views of what actually changes for you, kept to yourself."),
        ("life", "tint-purple", "Care tools",
         "Breathing, a craving pause, a safer-session plan, and a route home when you want one."),
        ("flask", "tint-pink", "Combination checker",
         "Plain-language cautions for combinations, including the medication you already take."),
        ("bell", "tint-amber", "Reminders that fit",
         "Check-in timers, a PEP window, and testing reminders, worded discreetly if you prefer."),
        ("watch", "tint-blue", "On your wrist",
         "Timers, check-ins and an emergency number on Apple Watch, without reaching for your phone."),
    ],

    "privacy_eyebrow": "Private by design",
    "privacy_h2": "Your phone, and nowhere else",
    "privacy_intro": "Privacy here is not a setting you go and switch on. It is how the app is built.",
    "privacy_checks": [
        "No account and no sign-up. There is no server holding your logs, because there is no server.",
        "No ads, no analytics, no trackers, and nothing is ever sold or shared.",
        "Lock it behind Face ID or a PIN, with everything encrypted on the device.",
        "Backups are optional and encrypted, and they go to your own iCloud Drive.",
        "Notifications can stay deliberately vague on the lock screen.",
    ],
    "privacy_link": "Read the full privacy policy",

    "proof_eyebrow": "Verify it yourself",
    "proof_h2": "Do not take our word for it",
    "proof_p": "ChillMate is open source. Every line that touches your data is in public, and the claim above is the kind you can check rather than trust.",
    "proof_fact": "There is not a single network call in the app's own code. No analytics SDK, no crash reporter, no <code>URLSession</code> anywhere. The only things that leave your phone are the ones you tap: a phone call, a link, a message you write yourself.",
    "proof_cta_repo": "Read the source",
    "proof_cta_store": "Where your data lives",
    "proof_caption": "Verified against ChillMate 4.2.1 (build 422).",

    "diagram_title": "Where your data goes",
    "diagram_you": "You",
    "diagram_phone": "Your iPhone",
    "diagram_icloud": "Your iCloud",
    "diagram_optional": "optional, encrypted",
    "diagram_server": "Our servers",
    "diagram_none": "there are none",

    "watch_h3": "It works when your phone is in a pocket",
    "watch_p": "Dose timers, hydration, discreet check-ins, a breathing exercise, and a one-tap call to your trusted contact or emergency services, all on Apple Watch, plus complications for your watch face and the Smart Stack.",
    "langs_h3": "It speaks your language",
    "langs_p": "The app and this site are available in English, Dutch, German, French and Spanish, and help resources follow the country you choose rather than the language you read.",

    "closing_callout": "ChillMate supports reflection, planning and personal wellbeing. It does not replace a clinician and it does not decide whether anything is safe. If someone may be in immediate danger, call your local emergency number.",

    # support page
    "support_title": "ChillMate · Support and help",
    "support_desc": "Contact, common questions, and real crisis and health services for your country.",
    "support_h1": "Support and help",
    "support_lede": "Questions, feedback, or a bug to report? ChillMate is made by one developer, so a real person reads every message.",
    "support_urgent": "<strong>In an emergency, do not wait for the app.</strong> If you or someone else may be in immediate danger, call your local emergency number now.",
    "support_contact_eyebrow": "Get in touch",
    "support_contact_h2": "Contact",
    "support_contact_p": "Email {email}. Replies usually take a few days. Including your iOS version and what you were doing when something went wrong helps a lot.",
    "support_email_btn": "Email support",
    "support_issue_btn": "Report an issue",
    "support_faq_eyebrow": "Common questions",
    "support_help_eyebrow": "Real services",
    "support_help_h2": "Get help from people, not an app",
    "support_help_p": "ChillMate is not a crisis service. Pick where you are and these organisations can help directly. This page prints and works offline, so it is still here when the signal is not.",
    "support_country_label": "Where are you?",
    "support_emergency_is": "Emergency number here:",
    "support_emergency_local": "your local emergency number",
    "support_print": "Print this page",

    "faq": [
        ("Is my data private?",
         "Yes. ChillMate keeps your information on your iPhone. There are no ads, no trackers, and nothing is sold. The app is open source, so you can read exactly what it does with your data."),
        ("How do I back up, or move to a new phone?",
         "Turn on iCloud backup in Settings to save an encrypted backup to your own iCloud Drive, or export an encrypted backup file. On a new device, restore from iCloud or import that file during setup."),
        ("How do I lock the app?",
         "In Settings, under Privacy and lock, turn on Face ID or set a PIN. You can also enable discreet notifications so lock-screen wording stays vague, and ChillMate hides its contents in the App Switcher and while your screen is recorded or mirrored."),
        ("How do tips work?",
         "The optional tip uses Apple In-App Purchase. It is entirely optional, it unlocks nothing, and every feature stays free for everyone."),
        ("How do I delete my data?",
         "You can delete individual entries or everything at once inside the app. Deleting the app removes its local data, and iCloud data can be removed from the backup controls or from iCloud settings."),
        ("Does ChillMate give medical advice?",
         "No. ChillMate helps you reflect, plan and organise. It does not diagnose, prescribe, or tell you whether anything is safe. Confirm anything important with a qualified professional."),
        ("Which countries does it support?",
         "ChillMate works anywhere. Help resources follow the country you pick in setup, with services built in for the Netherlands, Belgium, Germany, the UK, Ireland, France, Spain, the United States and Australia, and international fallbacks everywhere else."),
        ("Which languages does it speak?",
         "English, Dutch, German, French and Spanish, on the phone and on Apple Watch. You can set the language inside the app or in iOS Settings, and the one you changed last is the one that applies."),
    ],
}

STRINGS["nl"] = {
    "skip": "Naar de inhoud",
    "nav_home": "Home",
    "nav_privacy": "Privacy",
    "nav_support": "Hulp",
    "nav_about": "Over",
    "nav_github": "GitHub",
    "lang_label": "Taal",
    "theme_dark": "Donker",
    "theme_light": "Licht",
    "theme_hint": "Wissel van kleurthema",
    "to_top": "Terug naar boven",
    "made": "met zorg gemaakt in Nederland",
    "copy": "Kopiëren",
    "copied": "Gekopieerd",
    "call": "Bel",
    "open": "Open",
    "policy_en_note": "Het privacybeleid staat alleen in het Engels, zodat er één gezaghebbende tekst is in plaats van vijf die uit elkaar kunnen groeien.",

    "cat_emergency": "Hulpdiensten",
    "cat_crisis": "Crisis en zelfmoordpreventie",
    "cat_sexual_health": "Seksuele gezondheid en soa-tests",
    "cat_gp": "Je huisarts",
    "cat_drugs": "Drugsinformatie en harm reduction",
    "cat_assault": "Na seksueel geweld",
    "cat_lgbtq": "LHBTIQ+ steun",
    "cat_emergency_d": "Direct gevaar, bewusteloosheid, of iemand die niet wakker te krijgen is.",
    "cat_crisis_d": "Gratis en vertrouwelijk, als je jezelf iets zou kunnen aandoen of je niet veilig voelt.",
    "cat_sexual_health_d": "Soa-testen, PrEP, PEP-vragen, vaccinatie en seksuele gezondheid.",
    "cat_gp_d": "Wisselwerking van medicijnen, slaap, mentale gezondheid, middelengebruik en doorverwijzing.",
    "cat_drugs_d": "Betrouwbare, niet-veroordelende drugsinformatie en harm reduction.",
    "cat_assault_d": "Steun na geweld, dwang of twijfel over toestemming.",
    "cat_lgbtq_d": "Een luisterend oor, informatie en doorverwijzing.",
    "cat_generic_local": "Vraag het bij je lokale zorginstelling.",

    "home_title": "ChillMate · Een rustige, privéplek om voor jezelf te zorgen",
    "home_desc": "ChillMate houdt je logboek, plannen, herinneringen en veiligheidstools in één privéoverzicht. Alles blijft op je iPhone. Geen account, geen advertenties, geen tracking.",
    "h1": "Een rustige, privéplek om voor jezelf te zorgen.",
    "lede": "ChillMate houdt je logboek, reflecties, plannen, herinneringen en veiligheidstools in één privéoverzicht. Alles blijft op je iPhone. Geen account, geen advertenties, geen trackers, niets wordt verkocht.",
    "cta_support": "Hulp en ondersteuning",
    "cta_privacy": "Hoe privacy werkt",
    "status_note": "Nog niet in de App Store. Deze pagina linkt ernaar zodra dat wel zo is.",

    "walk_eyebrow": "Een kijkje binnen",
    "walk_h2": "Vijf schermen, en waar ze voor zijn.",
    "walk": [
        ("Home", "Alles in één oogopslag",
         "Je reeks, je score en de hulpmiddelen die bij dit moment passen. Hulp nodig staat altijd bovenaan, zodat ademhaling, grounding en een noodoproep nooit iets zijn dat je moet zoeken."),
        ("Paniekhulp", "Een kamer met het licht gedimd",
         "Een prikkelarme plek voor angst of als je je niet lekker voelt. Start de ademhalingstimer, loop de groundingstappen door, en bel pas iemand als je dat zelf wilt."),
        ("Privacyoverzicht", "Een eerlijke kaart van je eigen gegevens",
         "Wat op het toestel staat, wat er in een versleutelde back-up zou zitten, welke Gezondheid-categorieën je hebt toegestaan, en wat ChillMate nooit verstuurt. In de app, niet alleen in een beleidstekst."),
        ("Hulp", "Echte hulpverlening, offline",
         "Crisislijnen, seksuele gezondheid, drugs, LHBTIQ+ steun en praktische zorg voor het land dat je instelt. Het is een lijst op je telefoon, dus hij werkt zonder bereik."),
        ("Meer", "Niets weggestopt",
         "Profiel, instellingen, privacy, noodkaart en hulp, op één doorzoekbare plek in plaats van verspreid door menu's."),
    ],

    "features_eyebrow": "Wat het doet",
    "features": [
        ("book", "tint-blue", "Privélogboek",
         "Leg een nacht vast zoals jij hem wilt onthouden: slaap, hoe je je voelde, en wat daarna hielp."),
        ("chart", "tint-mint", "Jouw patronen",
         "Overzichten over dertig en negentig dagen van wat er echt voor je verandert, alleen voor jou."),
        ("life", "tint-purple", "Zorgtools",
         "Ademhaling, een pauze bij drang, een plan voor een veiligere sessie, en een route naar huis als je die wilt."),
        ("flask", "tint-pink", "Combinatiechecker",
         "Waarschuwingen in gewone taal over combinaties, inclusief de medicijnen die je al gebruikt."),
        ("bell", "tint-amber", "Herinneringen die passen",
         "Check-intimers, een PEP-venster en testherinneringen, discreet geformuleerd als je dat liever hebt."),
        ("watch", "tint-blue", "Op je pols",
         "Timers, check-ins en een noodnummer op Apple Watch, zonder naar je telefoon te grijpen."),
    ],

    "privacy_eyebrow": "Privé van opzet",
    "privacy_h2": "Je telefoon, en nergens anders",
    "privacy_intro": "Privacy is hier geen instelling die je nog moet aanzetten. Zo is de app gebouwd.",
    "privacy_checks": [
        "Geen account en geen aanmelding. Er is geen server met jouw logboek, want er is geen server.",
        "Geen advertenties, geen analytics, geen trackers, en er wordt nooit iets verkocht of gedeeld.",
        "Zet er Face ID of een pincode op, met alles versleuteld op het toestel.",
        "Back-ups zijn optioneel en versleuteld, en gaan naar je eigen iCloud Drive.",
        "Meldingen kunnen bewust vaag blijven op je vergrendelscherm.",
    ],
    "privacy_link": "Lees het volledige privacybeleid",

    "proof_eyebrow": "Controleer het zelf",
    "proof_h2": "Geloof ons niet op ons woord",
    "proof_p": "ChillMate is open source. Elke regel die je gegevens aanraakt staat openbaar, en de belofte hierboven is er een die je kunt controleren in plaats van vertrouwen.",
    "proof_fact": "In de code van de app staat geen enkele netwerkaanroep. Geen analytics-SDK, geen crashrapportage, nergens een <code>URLSession</code>. Het enige dat je telefoon verlaat, is wat jij zelf aantikt: een telefoongesprek, een link, een bericht dat je zelf schrijft.",
    "proof_cta_repo": "Lees de broncode",
    "proof_cta_store": "Waar je gegevens staan",
    "proof_caption": "Gecontroleerd op ChillMate 4.2.1 (build 422).",

    "diagram_title": "Waar je gegevens heen gaan",
    "diagram_you": "Jij",
    "diagram_phone": "Je iPhone",
    "diagram_icloud": "Jouw iCloud",
    "diagram_optional": "optioneel, versleuteld",
    "diagram_server": "Onze servers",
    "diagram_none": "die zijn er niet",

    "watch_h3": "Het werkt terwijl je telefoon in je zak zit",
    "watch_p": "Dosistimers, hydratatie, discrete check-ins, een ademhalingsoefening en met één tik bellen naar je vertrouwenscontact of de hulpdiensten, allemaal op Apple Watch, plus complicaties voor je wijzerplaat en de Smart Stack.",
    "langs_h3": "Het spreekt jouw taal",
    "langs_p": "De app en deze site zijn er in het Engels, Nederlands, Duits, Frans en Spaans, en de hulpbronnen volgen het land dat je kiest, niet de taal die je leest.",

    "closing_callout": "ChillMate ondersteunt reflectie, planning en je eigen welzijn. Het vervangt geen behandelaar en bepaalt niet of iets veilig is. Als iemand in direct gevaar kan zijn, bel dan je lokale alarmnummer.",

    "support_title": "ChillMate · Hulp en ondersteuning",
    "support_desc": "Contact, veelgestelde vragen en echte crisis- en zorgdiensten voor jouw land.",
    "support_h1": "Hulp en ondersteuning",
    "support_lede": "Vragen, feedback of een bug melden? ChillMate wordt door één ontwikkelaar gemaakt, dus er leest een echt mens mee.",
    "support_urgent": "<strong>Wacht in een noodgeval niet op de app.</strong> Als jij of iemand anders in direct gevaar kan zijn, bel dan nu je lokale alarmnummer.",
    "support_contact_eyebrow": "Neem contact op",
    "support_contact_h2": "Contact",
    "support_contact_p": "Mail naar {email}. Een antwoord duurt meestal een paar dagen. Je iOS-versie en wat je deed toen het misging, helpen enorm.",
    "support_email_btn": "Mail de ondersteuning",
    "support_issue_btn": "Meld een probleem",
    "support_faq_eyebrow": "Veelgestelde vragen",
    "support_help_eyebrow": "Echte hulpverlening",
    "support_help_h2": "Krijg hulp van mensen, niet van een app",
    "support_help_p": "ChillMate is geen crisisdienst. Kies waar je bent, dan kunnen deze organisaties je direct helpen. Deze pagina is printbaar en werkt offline, zodat hij er nog is als het bereik dat niet is.",
    "support_country_label": "Waar ben je?",
    "support_emergency_is": "Alarmnummer hier:",
    "support_emergency_local": "je lokale alarmnummer",
    "support_print": "Print deze pagina",

    "faq": [
        ("Zijn mijn gegevens privé?",
         "Ja. ChillMate houdt je gegevens op je iPhone. Geen advertenties, geen trackers, en er wordt niets verkocht. De app is open source, dus je kunt precies nalezen wat er met je gegevens gebeurt."),
        ("Hoe maak ik een back-up of stap ik over naar een nieuwe telefoon?",
         "Zet iCloud-back-up aan in Instellingen om een versleutelde back-up in je eigen iCloud Drive te bewaren, of exporteer een versleuteld back-upbestand. Op een nieuw toestel herstel je vanuit iCloud of importeer je dat bestand tijdens het instellen."),
        ("Hoe vergrendel ik de app?",
         "Zet in Instellingen, onder Privacy en vergrendeling, Face ID aan of stel een pincode in. Je kunt ook discrete meldingen aanzetten zodat de tekst op je vergrendelscherm vaag blijft, en ChillMate verbergt zijn inhoud in de app-switcher en tijdens schermopname of spiegelen."),
        ("Hoe werken fooien?",
         "De optionele fooi gaat via Apple In-App Purchase. Hij is volledig vrijwillig, ontgrendelt niets, en elke functie blijft voor iedereen gratis."),
        ("Hoe verwijder ik mijn gegevens?",
         "Je kunt losse items of alles in één keer verwijderen binnen de app. De app verwijderen wist de lokale gegevens, en iCloud-gegevens haal je weg via de back-upinstellingen of via iCloud."),
        ("Geeft ChillMate medisch advies?",
         "Nee. ChillMate helpt je reflecteren, plannen en ordenen. Het stelt geen diagnose, schrijft niets voor en zegt niet of iets veilig is. Leg belangrijke dingen voor aan een deskundige."),
        ("Welke landen worden ondersteund?",
         "ChillMate werkt overal. De hulpbronnen volgen het land dat je bij het instellen kiest, met ingebouwde diensten voor Nederland, België, Duitsland, het Verenigd Koninkrijk, Ierland, Frankrijk, Spanje, de Verenigde Staten en Australië, en internationale alternatieven daarbuiten."),
        ("Welke talen spreekt de app?",
         "Engels, Nederlands, Duits, Frans en Spaans, op de telefoon en op Apple Watch. Je stelt de taal in de app of in iOS-instellingen in, en de laatste die je wijzigde is degene die geldt."),
    ],
}

STRINGS["de"] = {
    "skip": "Zum Inhalt springen",
    "nav_home": "Start",
    "nav_privacy": "Datenschutz",
    "nav_support": "Hilfe",
    "nav_about": "Über",
    "nav_github": "GitHub",
    "lang_label": "Sprache",
    "theme_dark": "Dunkel",
    "theme_light": "Hell",
    "theme_hint": "Farbschema wechseln",
    "to_top": "Nach oben",
    "made": "mit Sorgfalt in den Niederlanden gemacht",
    "copy": "Kopieren",
    "copied": "Kopiert",
    "call": "Anrufen:",
    "open": "Öffnen:",
    "policy_en_note": "Die Datenschutzerklärung gibt es bewusst nur auf Englisch, damit es einen verbindlichen Text gibt statt fünf, die auseinanderlaufen können.",

    "cat_emergency": "Notruf",
    "cat_crisis": "Krisen- und Suizidhilfe",
    "cat_sexual_health": "Sexuelle Gesundheit und STI-Tests",
    "cat_gp": "Deine Ärztin oder dein Arzt",
    "cat_drugs": "Drogeninfo und Harm Reduction",
    "cat_assault": "Nach sexualisierter Gewalt",
    "cat_lgbtq": "LGBTQ+ Unterstützung",
    "cat_emergency_d": "Akute Gefahr, Bewusstlosigkeit oder jemand, der nicht aufwacht.",
    "cat_crisis_d": "Kostenlos und vertraulich, wenn du dir etwas antun könntest oder dich nicht sicher fühlst.",
    "cat_sexual_health_d": "STI-Tests, PrEP, PEP-Fragen, Impfungen und sexuelle Gesundheit.",
    "cat_gp_d": "Wechselwirkungen, Schlaf, psychische Gesundheit, Substanzgebrauch und Überweisungen.",
    "cat_drugs_d": "Verlässliche, wertungsfreie Drogeninformation und Harm Reduction.",
    "cat_assault_d": "Unterstützung nach Gewalt, Nötigung oder Zweifeln an Einvernehmlichkeit.",
    "cat_lgbtq_d": "Ein offenes Ohr, Information und Weitervermittlung.",
    "cat_generic_local": "Frag bei deiner örtlichen Gesundheitsstelle nach.",

    "home_title": "ChillMate · Ein ruhiger, privater Ort, um auf dich zu achten",
    "home_desc": "ChillMate hält Logs, Pläne, Erinnerungen und Sicherheitswerkzeuge in einer privaten Übersicht. Alles bleibt auf deinem iPhone. Kein Konto, keine Werbung, kein Tracking.",
    "h1": "Ein ruhiger, privater Ort, um auf dich zu achten.",
    "lede": "ChillMate hält deine Logs, Reflexionen, Pläne, Erinnerungen und Sicherheitswerkzeuge in einer privaten Übersicht. Alles bleibt auf deinem iPhone. Kein Konto, keine Werbung, keine Tracker, nichts wird verkauft.",
    "cta_support": "Hilfe und Unterstützung",
    "cta_privacy": "So funktioniert Datenschutz",
    "status_note": "Noch nicht im App Store. Diese Seite verlinkt ihn, sobald es so weit ist.",

    "walk_eyebrow": "Ein Blick hinein",
    "walk_h2": "Fünf Screens, und wofür sie da sind.",
    "walk": [
        ("Start", "Alles auf einen Blick",
         "Deine Serie, dein Score und die Werkzeuge, die zu diesem Moment passen. Jetzt Hilfe holen bleibt oben angeheftet, damit Atmung, Grounding und ein Notruf nie etwas sind, das du suchen musst."),
        ("Panikhilfe", "Ein Raum mit gedämpftem Licht",
         "Ein reizarmer Ort bei Angst oder Unwohlsein. Starte den Atemtimer, geh die Grounding-Schritte durch, und ruf erst jemanden an, wenn du das willst."),
        ("Datenschutz-Übersicht", "Eine ehrliche Karte deiner Daten",
         "Was auf dem Gerät liegt, was in einem verschlüsselten Backup wäre, welche Health-Kategorien du erlaubt hast, und was ChillMate nie sendet. In der App, nicht nur in einer Erklärung."),
        ("Hilfe", "Echte Anlaufstellen, offline",
         "Krisentelefone, sexuelle Gesundheit, Drogen, LGBTQ+ Unterstützung und praktische Hilfe für das Land, das du einstellst. Eine Liste auf deinem Handy, also auch ohne Empfang."),
        ("Mehr", "Nichts versteckt",
         "Profil, Einstellungen, Datenschutz, Notfallkarte und Hilfe an einem durchsuchbaren Ort statt verstreut in Menüs."),
    ],

    "features_eyebrow": "Was es kann",
    "features": [
        ("book", "tint-blue", "Privates Log",
         "Halte eine Nacht so fest, wie du sie erinnern willst: Schlaf, wie es dir ging, und was danach geholfen hat."),
        ("chart", "tint-mint", "Deine Muster",
         "Ansichten über dreißig und neunzig Tage, was sich für dich wirklich ändert, nur für dich."),
        ("life", "tint-purple", "Care-Werkzeuge",
         "Atmung, eine Pause bei Verlangen, ein Plan für eine sicherere Session, und ein Weg nach Hause, wenn du ihn willst."),
        ("flask", "tint-pink", "Kombinationscheck",
         "Hinweise in klarer Sprache zu Kombinationen, auch mit den Medikamenten, die du bereits nimmst."),
        ("bell", "tint-amber", "Erinnerungen, die passen",
         "Check-in-Timer, ein PEP-Fenster und Test-Erinnerungen, auf Wunsch diskret formuliert."),
        ("watch", "tint-blue", "An deinem Handgelenk",
         "Timer, Check-ins und eine Notrufnummer auf der Apple Watch, ohne zum Handy zu greifen."),
    ],

    "privacy_eyebrow": "Privat gebaut",
    "privacy_h2": "Dein Handy, und sonst nirgends",
    "privacy_intro": "Datenschutz ist hier keine Einstellung, die du erst aktivierst. So ist die App gebaut.",
    "privacy_checks": [
        "Kein Konto, keine Anmeldung. Es gibt keinen Server mit deinen Logs, weil es keinen Server gibt.",
        "Keine Werbung, keine Analytics, keine Tracker, und nichts wird je verkauft oder geteilt.",
        "Sichere sie mit Face ID oder PIN, alles auf dem Gerät verschlüsselt.",
        "Backups sind optional und verschlüsselt und gehen in deine eigene iCloud Drive.",
        "Mitteilungen können auf dem Sperrbildschirm bewusst vage bleiben.",
    ],
    "privacy_link": "Vollständige Datenschutzerklärung lesen",

    "proof_eyebrow": "Prüf es selbst",
    "proof_h2": "Glaub uns nicht einfach so",
    "proof_p": "ChillMate ist Open Source. Jede Zeile, die deine Daten berührt, ist öffentlich, und das Versprechen oben ist eines, das du prüfen kannst statt es glauben zu müssen.",
    "proof_fact": "Im Code der App gibt es keinen einzigen Netzwerkaufruf. Kein Analytics-SDK, kein Crash-Reporter, nirgends eine <code>URLSession</code>. Dein Handy verlässt nur, was du selbst antippst: ein Anruf, ein Link, eine Nachricht, die du schreibst.",
    "proof_cta_repo": "Quellcode lesen",
    "proof_cta_store": "Wo deine Daten liegen",
    "proof_caption": "Geprüft an ChillMate 4.2.1 (Build 422).",

    "diagram_title": "Wohin deine Daten gehen",
    "diagram_you": "Du",
    "diagram_phone": "Dein iPhone",
    "diagram_icloud": "Deine iCloud",
    "diagram_optional": "optional, verschlüsselt",
    "diagram_server": "Unsere Server",
    "diagram_none": "gibt es nicht",

    "watch_h3": "Es funktioniert, während das Handy in der Tasche bleibt",
    "watch_p": "Dosis-Timer, Trinken, diskrete Check-ins, eine Atemübung und ein Anruf mit einem Tipp bei deiner Vertrauensperson oder dem Notruf, alles auf der Apple Watch, dazu Komplikationen für Zifferblatt und Smart Stack.",
    "langs_h3": "Es spricht deine Sprache",
    "langs_p": "App und Website gibt es auf Englisch, Niederländisch, Deutsch, Französisch und Spanisch, und die Hilfsangebote richten sich nach deinem Land, nicht nach deiner Lesesprache.",

    "closing_callout": "ChillMate unterstützt Reflexion, Planung und dein Wohlbefinden. Es ersetzt keine Fachperson und entscheidet nicht, ob etwas sicher ist. Wenn jemand in akuter Gefahr sein könnte, ruf den örtlichen Notruf.",

    "support_title": "ChillMate · Hilfe und Unterstützung",
    "support_desc": "Kontakt, häufige Fragen und echte Krisen- und Gesundheitsangebote für dein Land.",
    "support_h1": "Hilfe und Unterstützung",
    "support_lede": "Fragen, Feedback oder ein Fehler? ChillMate wird von einer einzelnen Person entwickelt, es liest also ein echter Mensch mit.",
    "support_urgent": "<strong>Warte im Notfall nicht auf die App.</strong> Wenn du oder jemand anderes in akuter Gefahr sein könnte, ruf jetzt den örtlichen Notruf.",
    "support_contact_eyebrow": "Kontakt aufnehmen",
    "support_contact_h2": "Kontakt",
    "support_contact_p": "Schreib an {email}. Eine Antwort dauert meist ein paar Tage. Deine iOS-Version und was du gerade getan hast, helfen sehr.",
    "support_email_btn": "Support anschreiben",
    "support_issue_btn": "Problem melden",
    "support_faq_eyebrow": "Häufige Fragen",
    "support_help_eyebrow": "Echte Anlaufstellen",
    "support_help_h2": "Hilfe von Menschen, nicht von einer App",
    "support_help_p": "ChillMate ist kein Krisendienst. Wähl aus, wo du bist, dann helfen dir diese Stellen direkt. Diese Seite lässt sich drucken und funktioniert offline, damit sie da ist, wenn der Empfang es nicht ist.",
    "support_country_label": "Wo bist du?",
    "support_emergency_is": "Notruf hier:",
    "support_emergency_local": "dein örtlicher Notruf",
    "support_print": "Diese Seite drucken",

    "faq": [
        ("Sind meine Daten privat?",
         "Ja. ChillMate hält deine Daten auf deinem iPhone. Keine Werbung, keine Tracker, nichts wird verkauft. Die App ist Open Source, du kannst also genau nachlesen, was mit deinen Daten passiert."),
        ("Wie mache ich ein Backup oder wechsle das Handy?",
         "Aktiviere iCloud-Backup in den Einstellungen, um ein verschlüsseltes Backup in deiner eigenen iCloud Drive zu speichern, oder exportiere eine verschlüsselte Backup-Datei. Auf einem neuen Gerät stellst du beim Einrichten aus iCloud wieder her oder importierst die Datei."),
        ("Wie sperre ich die App?",
         "Aktiviere in den Einstellungen unter Datenschutz und Sperre Face ID oder setze eine PIN. Du kannst auch diskrete Mitteilungen einschalten, damit der Sperrbildschirm vage bleibt, und ChillMate verbirgt seinen Inhalt im App-Umschalter sowie bei Bildschirmaufnahme oder Spiegelung."),
        ("Wie funktionieren Trinkgelder?",
         "Das optionale Trinkgeld läuft über Apple In-App-Kauf. Es ist völlig freiwillig, schaltet nichts frei, und jede Funktion bleibt für alle kostenlos."),
        ("Wie lösche ich meine Daten?",
         "Du kannst einzelne Einträge oder alles auf einmal in der App löschen. Die App zu löschen entfernt die lokalen Daten, iCloud-Daten entfernst du über die Backup-Einstellungen oder über iCloud."),
        ("Gibt ChillMate medizinischen Rat?",
         "Nein. ChillMate hilft beim Reflektieren, Planen und Ordnen. Es stellt keine Diagnose, verschreibt nichts und sagt nicht, ob etwas sicher ist. Kläre Wichtiges mit einer Fachperson."),
        ("Welche Länder werden unterstützt?",
         "ChillMate funktioniert überall. Die Hilfsangebote richten sich nach dem Land, das du beim Einrichten wählst, mit eingebauten Angeboten für die Niederlande, Belgien, Deutschland, das Vereinigte Königreich, Irland, Frankreich, Spanien, die USA und Australien, und internationalen Alternativen überall sonst."),
        ("Welche Sprachen spricht die App?",
         "Englisch, Niederländisch, Deutsch, Französisch und Spanisch, auf dem Handy und auf der Apple Watch. Die Sprache stellst du in der App oder in den iOS-Einstellungen ein, es gilt die zuletzt geänderte."),
    ],
}

STRINGS["fr"] = {
    "skip": "Aller au contenu",
    "nav_home": "Accueil",
    "nav_privacy": "Confidentialité",
    "nav_support": "Aide",
    "nav_about": "À propos",
    "nav_github": "GitHub",
    "lang_label": "Langue",
    "theme_dark": "Sombre",
    "theme_light": "Clair",
    "theme_hint": "Changer de thème",
    "to_top": "Retour en haut",
    "made": "fait avec soin aux Pays-Bas",
    "copy": "Copier",
    "copied": "Copié",
    "call": "Appeler",
    "open": "Ouvrir",
    "policy_en_note": "La politique de confidentialité reste en anglais uniquement, pour qu'il existe un seul texte de référence plutôt que cinq qui pourraient diverger.",

    "cat_emergency": "Secours d'urgence",
    "cat_crisis": "Crise et prévention du suicide",
    "cat_sexual_health": "Santé sexuelle et dépistage IST",
    "cat_gp": "Votre médecin",
    "cat_drugs": "Information drogues et réduction des risques",
    "cat_assault": "Après une agression sexuelle",
    "cat_lgbtq": "Soutien LGBTQ+",
    "cat_emergency_d": "Danger immédiat, perte de connaissance, ou une personne qu'on ne parvient pas à réveiller.",
    "cat_crisis_d": "Gratuit et confidentiel, si vous risquez de vous faire du mal ou ne vous sentez pas en sécurité.",
    "cat_sexual_health_d": "Dépistage IST, PrEP, questions PEP, vaccination et santé sexuelle.",
    "cat_gp_d": "Interactions médicamenteuses, sommeil, santé mentale, consommation et orientation.",
    "cat_drugs_d": "Information fiable et sans jugement, et réduction des risques.",
    "cat_assault_d": "Soutien après une agression, une contrainte ou un doute sur le consentement.",
    "cat_lgbtq_d": "Une écoute, de l'information et une orientation.",
    "cat_generic_local": "Renseignez-vous auprès de votre service de santé local.",

    "home_title": "ChillMate · Un endroit calme et privé pour prendre soin de vous",
    "home_desc": "ChillMate réunit vos notes, plans, rappels et outils de sécurité dans un aperçu privé. Tout reste sur votre iPhone. Sans compte, sans publicité, sans pistage.",
    "h1": "Un endroit calme et privé pour prendre soin de vous.",
    "lede": "ChillMate réunit vos notes, réflexions, plans, rappels et outils de sécurité dans un aperçu privé. Tout reste sur votre iPhone. Sans compte, sans publicité, sans traceurs, rien n'est vendu.",
    "cta_support": "Aide et soutien",
    "cta_privacy": "Comment la confidentialité fonctionne",
    "status_note": "Pas encore sur l'App Store. Cette page y renverra dès que ce sera le cas.",

    "walk_eyebrow": "Un aperçu",
    "walk_h2": "Cinq écrans, et à quoi chacun sert.",
    "walk": [
        ("Accueil", "Tout d'un coup d'œil",
         "Votre série, votre score et les outils adaptés au moment. Obtenir de l'aide reste épinglé en haut, pour que la respiration, l'ancrage et un appel d'urgence ne soient jamais à chercher."),
        ("Soutien en cas de panique", "Une pièce aux lumières baissées",
         "Un espace à faible stimulation pour l'anxiété ou un malaise. Lancez le minuteur de respiration, suivez les étapes d'ancrage, et n'appelez quelqu'un que si vous le décidez."),
        ("Tableau de confidentialité", "Une carte honnête de vos données",
         "Ce qui est stocké sur l'appareil, ce que contiendrait une sauvegarde chiffrée, les catégories Santé que vous avez autorisées, et ce que ChillMate n'envoie jamais. Dans l'app, pas seulement dans une politique."),
        ("Aide", "De vrais services, hors ligne",
         "Lignes de crise, santé sexuelle, drogues, soutien LGBTQ+ et aide pratique pour le pays que vous choisissez. C'est une liste sur votre téléphone, donc elle marche sans réseau."),
        ("Plus", "Rien d'enfoui",
         "Profil, réglages, confidentialité, carte d'urgence et aide, dans un seul endroit consultable plutôt qu'éparpillés dans des menus."),
    ],

    "features_eyebrow": "Ce que ça fait",
    "features": [
        ("book", "tint-blue", "Journal privé",
         "Notez une soirée comme vous voulez vous en souvenir : sommeil, ressenti, et ce qui a aidé ensuite."),
        ("chart", "tint-mint", "Vos tendances",
         "Des vues sur trente et quatre-vingt-dix jours de ce qui change vraiment pour vous, pour vous seul."),
        ("life", "tint-purple", "Outils de soin",
         "Respiration, pause face à l'envie, plan pour une session plus sûre, et un trajet de retour si vous le voulez."),
        ("flask", "tint-pink", "Vérificateur de combinaisons",
         "Des mises en garde en langage clair sur les associations, y compris avec vos médicaments actuels."),
        ("bell", "tint-amber", "Des rappels qui vous vont",
         "Minuteurs de check-in, fenêtre PEP et rappels de dépistage, formulés discrètement si vous préférez."),
        ("watch", "tint-blue", "À votre poignet",
         "Minuteurs, check-ins et un numéro d'urgence sur Apple Watch, sans sortir votre téléphone."),
    ],

    "privacy_eyebrow": "Privé par conception",
    "privacy_h2": "Votre téléphone, et nulle part ailleurs",
    "privacy_intro": "Ici, la confidentialité n'est pas une option à activer. C'est la façon dont l'app est construite.",
    "privacy_checks": [
        "Aucun compte, aucune inscription. Aucun serveur ne détient vos notes, parce qu'il n'y a pas de serveur.",
        "Pas de publicité, pas d'analytique, pas de traceurs, et rien n'est jamais vendu ni partagé.",
        "Verrouillez avec Face ID ou un code, tout étant chiffré sur l'appareil.",
        "Les sauvegardes sont facultatives et chiffrées, et vont dans votre propre iCloud Drive.",
        "Les notifications peuvent rester volontairement vagues sur l'écran verrouillé.",
    ],
    "privacy_link": "Lire la politique de confidentialité complète",

    "proof_eyebrow": "Vérifiez vous-même",
    "proof_h2": "Ne nous croyez pas sur parole",
    "proof_p": "ChillMate est open source. Chaque ligne qui touche vos données est publique, et la promesse ci-dessus est de celles qu'on peut vérifier plutôt que croire.",
    "proof_fact": "Le code de l'app ne contient aucun appel réseau. Aucun SDK d'analytique, aucun rapport de plantage, aucune <code>URLSession</code> nulle part. Seul ce que vous touchez quitte votre téléphone : un appel, un lien, un message que vous écrivez.",
    "proof_cta_repo": "Lire le code source",
    "proof_cta_store": "Où vivent vos données",
    "proof_caption": "Vérifié sur ChillMate 4.2.1 (build 422).",

    "diagram_title": "Où vont vos données",
    "diagram_you": "Vous",
    "diagram_phone": "Votre iPhone",
    "diagram_icloud": "Votre iCloud",
    "diagram_optional": "facultatif, chiffré",
    "diagram_server": "Nos serveurs",
    "diagram_none": "il n'y en a pas",

    "watch_h3": "Ça marche pendant que le téléphone reste dans la poche",
    "watch_p": "Minuteurs de dose, hydratation, check-ins discrets, un exercice de respiration et un appel en un geste vers votre personne de confiance ou les secours, le tout sur Apple Watch, avec des complications pour le cadran et la Smart Stack.",
    "langs_h3": "Ça parle votre langue",
    "langs_p": "L'app et ce site existent en anglais, néerlandais, allemand, français et espagnol, et les ressources d'aide suivent le pays que vous choisissez, pas la langue que vous lisez.",

    "closing_callout": "ChillMate accompagne la réflexion, la planification et votre bien-être. Il ne remplace pas un professionnel et ne décide pas si quelque chose est sûr. Si une personne peut être en danger immédiat, appelez votre numéro d'urgence local.",

    "support_title": "ChillMate · Aide et soutien",
    "support_desc": "Contact, questions fréquentes, et de vrais services de crise et de santé pour votre pays.",
    "support_h1": "Aide et soutien",
    "support_lede": "Une question, un retour, un bug ? ChillMate est fait par une seule personne, donc un humain lit chaque message.",
    "support_urgent": "<strong>En cas d'urgence, n'attendez pas l'app.</strong> Si vous ou quelqu'un d'autre pouvez être en danger immédiat, appelez tout de suite votre numéro d'urgence local.",
    "support_contact_eyebrow": "Nous écrire",
    "support_contact_h2": "Contact",
    "support_contact_p": "Écrivez à {email}. La réponse prend en général quelques jours. Préciser votre version d'iOS et ce que vous faisiez au moment du problème aide beaucoup.",
    "support_email_btn": "Écrire au support",
    "support_issue_btn": "Signaler un problème",
    "support_faq_eyebrow": "Questions fréquentes",
    "support_help_eyebrow": "De vrais services",
    "support_help_h2": "De l'aide humaine, pas une application",
    "support_help_p": "ChillMate n'est pas un service de crise. Indiquez où vous êtes et ces organisations pourront vous aider directement. Cette page s'imprime et fonctionne hors ligne, pour être encore là quand le réseau ne l'est plus.",
    "support_country_label": "Où êtes-vous ?",
    "support_emergency_is": "Numéro d'urgence ici :",
    "support_emergency_local": "votre numéro d'urgence local",
    "support_print": "Imprimer cette page",

    "faq": [
        ("Mes données sont-elles privées ?",
         "Oui. ChillMate garde vos informations sur votre iPhone. Pas de publicité, pas de traceurs, rien n'est vendu. L'app est open source, vous pouvez donc lire exactement ce qu'elle fait de vos données."),
        ("Comment sauvegarder, ou changer de téléphone ?",
         "Activez la sauvegarde iCloud dans les réglages pour enregistrer une sauvegarde chiffrée dans votre propre iCloud Drive, ou exportez un fichier de sauvegarde chiffré. Sur un nouvel appareil, restaurez depuis iCloud ou importez ce fichier pendant la configuration."),
        ("Comment verrouiller l'app ?",
         "Dans les réglages, sous Confidentialité et verrouillage, activez Face ID ou définissez un code. Vous pouvez aussi activer les notifications discrètes pour que l'écran verrouillé reste vague, et ChillMate masque son contenu dans le sélecteur d'apps ainsi que pendant un enregistrement ou une recopie d'écran."),
        ("Comment fonctionnent les pourboires ?",
         "Le pourboire facultatif passe par l'achat intégré Apple. Il est entièrement volontaire, ne débloque rien, et toutes les fonctions restent gratuites pour tout le monde."),
        ("Comment supprimer mes données ?",
         "Vous pouvez supprimer des entrées une par une ou tout d'un coup dans l'app. Supprimer l'app efface ses données locales, et les données iCloud se retirent depuis les réglages de sauvegarde ou depuis iCloud."),
        ("ChillMate donne-t-il des conseils médicaux ?",
         "Non. ChillMate aide à réfléchir, planifier et organiser. Il ne diagnostique pas, ne prescrit pas et ne dit pas si quelque chose est sûr. Confirmez l'important auprès d'un professionnel qualifié."),
        ("Quels pays sont pris en charge ?",
         "ChillMate fonctionne partout. Les ressources d'aide suivent le pays choisi à la configuration, avec des services intégrés pour les Pays-Bas, la Belgique, l'Allemagne, le Royaume-Uni, l'Irlande, la France, l'Espagne, les États-Unis et l'Australie, et des solutions internationales ailleurs."),
        ("Quelles langues l'app parle-t-elle ?",
         "Anglais, néerlandais, allemand, français et espagnol, sur le téléphone et sur Apple Watch. Vous réglez la langue dans l'app ou dans les réglages iOS, et c'est le dernier changement qui s'applique."),
    ],
}

STRINGS["es"] = {
    "skip": "Saltar al contenido",
    "nav_home": "Inicio",
    "nav_privacy": "Privacidad",
    "nav_support": "Ayuda",
    "nav_about": "Acerca de",
    "nav_github": "GitHub",
    "lang_label": "Idioma",
    "theme_dark": "Oscuro",
    "theme_light": "Claro",
    "theme_hint": "Cambiar de tema",
    "to_top": "Volver arriba",
    "made": "hecho con cuidado en los Países Bajos",
    "copy": "Copiar",
    "copied": "Copiado",
    "call": "Llamar",
    "open": "Abrir",
    "policy_en_note": "La política de privacidad se mantiene solo en inglés, para que haya un único texto de referencia en lugar de cinco que puedan separarse.",

    "cat_emergency": "Emergencias",
    "cat_crisis": "Crisis y prevención del suicidio",
    "cat_sexual_health": "Salud sexual y pruebas de ITS",
    "cat_gp": "Tu médico",
    "cat_drugs": "Información sobre drogas y reducción de daños",
    "cat_assault": "Tras una agresión sexual",
    "cat_lgbtq": "Apoyo LGTBIQ+",
    "cat_emergency_d": "Peligro inmediato, pérdida de conciencia, o alguien que no despierta.",
    "cat_crisis_d": "Gratuito y confidencial, si podrías hacerte daño o no te sientes a salvo.",
    "cat_sexual_health_d": "Pruebas de ITS, PrEP, dudas sobre PEP, vacunación y salud sexual.",
    "cat_gp_d": "Interacciones de medicamentos, sueño, salud mental, consumo y derivaciones.",
    "cat_drugs_d": "Información fiable y sin juicios, y reducción de daños.",
    "cat_assault_d": "Apoyo tras una agresión, coacción o dudas sobre el consentimiento.",
    "cat_lgbtq_d": "Escucha, información y derivación.",
    "cat_generic_local": "Pregunta en tu servicio de salud local.",

    "home_title": "ChillMate · Un lugar tranquilo y privado para cuidarte",
    "home_desc": "ChillMate reúne tus registros, planes, recordatorios y herramientas de seguridad en un resumen privado. Todo se queda en tu iPhone. Sin cuenta, sin anuncios, sin rastreo.",
    "h1": "Un lugar tranquilo y privado para cuidarte.",
    "lede": "ChillMate reúne tus registros, reflexiones, planes, recordatorios y herramientas de seguridad en un resumen privado. Todo se queda en tu iPhone. Sin cuenta, sin anuncios, sin rastreadores, nada se vende.",
    "cta_support": "Ayuda y apoyo",
    "cta_privacy": "Cómo funciona la privacidad",
    "status_note": "Todavía no está en la App Store. Esta página enlazará ahí en cuanto lo esté.",

    "walk_eyebrow": "Un vistazo por dentro",
    "walk_h2": "Cinco pantallas, y para qué sirve cada una.",
    "walk": [
        ("Inicio", "Todo de un vistazo",
         "Tu racha, tu puntuación y las herramientas que encajan con este momento. Pedir ayuda queda fijado arriba, para que respirar, hacer grounding o llamar a emergencias nunca sea algo que haya que buscar."),
        ("Apoyo en pánico", "Una habitación con la luz baja",
         "Un espacio de baja estimulación para la ansiedad o el malestar. Empieza el temporizador de respiración, sigue los pasos de grounding, y llama a alguien solo si tú lo decides."),
        ("Panel de privacidad", "Un mapa honesto de tus datos",
         "Qué se guarda en el dispositivo, qué contendría una copia cifrada, qué categorías de Salud has permitido, y qué no envía ChillMate nunca. En la app, no solo en una política."),
        ("Ayuda", "Servicios reales, sin conexión",
         "Líneas de crisis, salud sexual, drogas, apoyo LGTBIQ+ y cuidado práctico para el país que elijas. Es una lista en tu teléfono, así que funciona sin cobertura."),
        ("Más", "Nada escondido",
         "Perfil, ajustes, privacidad, tarjeta de emergencia y ayuda, en un único sitio que se puede buscar en lugar de repartidos por menús."),
    ],

    "features_eyebrow": "Qué hace",
    "features": [
        ("book", "tint-blue", "Registro privado",
         "Anota una noche como quieras recordarla: sueño, cómo te sentiste, y qué ayudó después."),
        ("chart", "tint-mint", "Tus patrones",
         "Vistas de treinta y noventa días de lo que de verdad cambia para ti, solo para ti."),
        ("life", "tint-purple", "Herramientas de cuidado",
         "Respiración, una pausa ante el impulso, un plan para una sesión más segura, y una ruta a casa cuando la quieras."),
        ("flask", "tint-pink", "Comprobador de combinaciones",
         "Avisos en lenguaje claro sobre combinaciones, incluida la medicación que ya tomas."),
        ("bell", "tint-amber", "Recordatorios que encajan",
         "Temporizadores de check-in, una ventana de PEP y recordatorios de pruebas, redactados con discreción si lo prefieres."),
        ("watch", "tint-blue", "En tu muñeca",
         "Temporizadores, check-ins y un número de emergencia en el Apple Watch, sin sacar el teléfono."),
    ],

    "privacy_eyebrow": "Privado por diseño",
    "privacy_h2": "Tu teléfono, y ningún otro sitio",
    "privacy_intro": "Aquí la privacidad no es un ajuste que haya que activar. Es cómo está hecha la app.",
    "privacy_checks": [
        "Sin cuenta y sin registro. No hay ningún servidor con tus registros, porque no hay servidor.",
        "Sin anuncios, sin analítica, sin rastreadores, y nunca se vende ni se comparte nada.",
        "Bloquéala con Face ID o un PIN, con todo cifrado en el dispositivo.",
        "Las copias de seguridad son opcionales y cifradas, y van a tu propio iCloud Drive.",
        "Las notificaciones pueden quedarse deliberadamente vagas en la pantalla de bloqueo.",
    ],
    "privacy_link": "Leer la política de privacidad completa",

    "proof_eyebrow": "Compruébalo tú",
    "proof_h2": "No nos creas sin más",
    "proof_p": "ChillMate es de código abierto. Cada línea que toca tus datos es pública, y la promesa de arriba es de las que se pueden comprobar en vez de creer.",
    "proof_fact": "En el código de la app no hay ni una sola llamada de red. Ningún SDK de analítica, ningún informe de fallos, ninguna <code>URLSession</code> en ninguna parte. De tu teléfono solo sale lo que tú tocas: una llamada, un enlace, un mensaje que escribes tú.",
    "proof_cta_repo": "Leer el código",
    "proof_cta_store": "Dónde viven tus datos",
    "proof_caption": "Verificado en ChillMate 4.2.1 (build 422).",

    "diagram_title": "Adónde van tus datos",
    "diagram_you": "Tú",
    "diagram_phone": "Tu iPhone",
    "diagram_icloud": "Tu iCloud",
    "diagram_optional": "opcional, cifrado",
    "diagram_server": "Nuestros servidores",
    "diagram_none": "no existen",

    "watch_h3": "Funciona con el teléfono en el bolsillo",
    "watch_p": "Temporizadores de dosis, hidratación, check-ins discretos, un ejercicio de respiración y una llamada con un toque a tu contacto de confianza o a emergencias, todo en el Apple Watch, además de complicaciones para la esfera y la Smart Stack.",
    "langs_h3": "Habla tu idioma",
    "langs_p": "La app y este sitio están en inglés, neerlandés, alemán, francés y español, y los recursos de ayuda siguen al país que elijas, no al idioma en que lees.",

    "closing_callout": "ChillMate acompaña la reflexión, la planificación y tu bienestar. No sustituye a un profesional ni decide si algo es seguro. Si alguien puede estar en peligro inmediato, llama a tu número de emergencias local.",

    "support_title": "ChillMate · Ayuda y apoyo",
    "support_desc": "Contacto, preguntas frecuentes y servicios reales de crisis y salud para tu país.",
    "support_h1": "Ayuda y apoyo",
    "support_lede": "¿Preguntas, comentarios o un fallo que contar? ChillMate lo hace una sola persona, así que hay alguien de verdad leyendo cada mensaje.",
    "support_urgent": "<strong>En una emergencia, no esperes a la app.</strong> Si tú u otra persona podéis estar en peligro inmediato, llama ya a tu número de emergencias local.",
    "support_contact_eyebrow": "Escríbenos",
    "support_contact_h2": "Contacto",
    "support_contact_p": "Escribe a {email}. La respuesta suele tardar unos días. Indicar tu versión de iOS y qué estabas haciendo cuando falló ayuda mucho.",
    "support_email_btn": "Escribir a soporte",
    "support_issue_btn": "Informar de un problema",
    "support_faq_eyebrow": "Preguntas frecuentes",
    "support_help_eyebrow": "Servicios reales",
    "support_help_h2": "Ayuda de personas, no de una app",
    "support_help_p": "ChillMate no es un servicio de crisis. Elige dónde estás y estas organizaciones pueden ayudarte directamente. Esta página se imprime y funciona sin conexión, para seguir aquí cuando la cobertura no esté.",
    "support_country_label": "¿Dónde estás?",
    "support_emergency_is": "Número de emergencias aquí:",
    "support_emergency_local": "tu número de emergencias local",
    "support_print": "Imprimir esta página",

    "faq": [
        ("¿Mis datos son privados?",
         "Sí. ChillMate guarda tu información en tu iPhone. Sin anuncios, sin rastreadores, y no se vende nada. La app es de código abierto, así que puedes leer exactamente qué hace con tus datos."),
        ("¿Cómo hago una copia de seguridad o cambio de teléfono?",
         "Activa la copia de iCloud en Ajustes para guardar una copia cifrada en tu propio iCloud Drive, o exporta un archivo de copia cifrado. En un dispositivo nuevo, restaura desde iCloud o importa ese archivo durante la configuración."),
        ("¿Cómo bloqueo la app?",
         "En Ajustes, dentro de Privacidad y bloqueo, activa Face ID o pon un PIN. También puedes activar las notificaciones discretas para que el texto de la pantalla de bloqueo sea vago, y ChillMate oculta su contenido en el selector de apps y durante grabaciones o duplicado de pantalla."),
        ("¿Cómo funcionan las propinas?",
         "La propina opcional usa la compra integrada de Apple. Es totalmente voluntaria, no desbloquea nada, y todas las funciones siguen siendo gratis para todo el mundo."),
        ("¿Cómo borro mis datos?",
         "Puedes borrar entradas sueltas o todo de una vez dentro de la app. Borrar la app elimina sus datos locales, y los datos de iCloud se quitan desde los ajustes de copia o desde iCloud."),
        ("¿ChillMate da consejo médico?",
         "No. ChillMate ayuda a reflexionar, planificar y ordenar. No diagnostica, no receta y no dice si algo es seguro. Consulta lo importante con un profesional cualificado."),
        ("¿Qué países admite?",
         "ChillMate funciona en cualquier sitio. Los recursos de ayuda siguen al país que elijas en la configuración, con servicios integrados para los Países Bajos, Bélgica, Alemania, el Reino Unido, Irlanda, Francia, España, Estados Unidos y Australia, y alternativas internacionales en el resto."),
        ("¿Qué idiomas habla?",
         "Inglés, neerlandés, alemán, francés y español, en el teléfono y en el Apple Watch. El idioma se elige en la app o en los ajustes de iOS, y vale el último que hayas cambiado."),
    ],
}
